# [AI Innovation Square 릴레이 온라인 특강: Python] 


## 10. 함수형 패러다임(2)


- Functional Paradigm (FP)
- 함수를 수학함수로 생각하고 수학처럼 프로그래밍
- 함수 :first class object 


> 책추천: Clean Python

In [1]:
def x():
    pass

In [3]:
type(x) #function의 인스턴스

function

In [4]:
a=[x]

In [5]:
a[0]()

In [10]:
a=input()
b=int(a)
c=[]
for i in range(b): #for 문
    c.append(i)

5


In [11]:
c

[0, 1, 2, 3, 4]

- comprehension으로 간결하게
    - list, dict, sets comp

In [13]:
[x for x in range(int(input()))] #list comp

5


[0, 1, 2, 3, 4]

### generator expression
- tuple comp
- yield

In [14]:
(x for x in range(int(input())))

5


<generator object <genexpr> at 0x7ffad82a72d0>

##### recursion
- 수식표현 가능하면 구현 가능
- 파이썬에서 느려서 사용하지 않음
- 메모리 소비 큼

##### list processing(Lisp)
- 동시에 여러개 값 처리
- immutable (eg. tensorflow, pytorch)



- side-effect 없음
- 문보다 식(epxression)
- what > how
- 파이썬은 멀티패러다임 언어

### Encapsulation 캠슐화
- 접근 제한 
    - python class는 외부에서 내부 접근 가능

### callable
- class, function , `__call__` 이 내부에 정의된 인스턴스
- () 붙일 수 있어 함수처럼 사용
> function,클래스, 클래스의 instance에 `__call__`

In [17]:
type(1) #int 인스턴스

int

In [16]:
type(int)#int는  class 

type

In [18]:
callable(int) #int class 

True

In [19]:
int() #x=0 기본값

0

In [20]:
import tensorflow as tf

In [22]:
type(tf.keras.layers.Dense) #클래스

type

In [23]:
tf.keras.layers.Dense(10,activation='softmax') #인스턴스

In [28]:
import inspect
print(inspect.getsource(tf.keras.layers.Layer))

class Layer(module.Module, version_utils.LayerVersionSelector):
  """This is the class from which all layers inherit.

  A layer is a callable object that takes as input one or more tensors and
  that outputs one or more tensors. It involves *computation*, defined
  in the `call()` method, and a *state* (weight variables), defined
  either in the constructor `__init__()` or in the `build()` method.

  Users will just instantiate a layer and then treat it as a callable.

  Arguments:
    trainable: Boolean, whether the layer's variables should be trainable.
    name: String name of the layer.
    dtype: The dtype of the layer's computations and weights (default of
      `None` means use `tf.keras.backend.floatx` in TensorFlow 2, or the type
      of the first input in TensorFlow 1).
    dynamic: Set this to `True` if your layer should only be run eagerly, and
      should not be used to generate a static computation graph.
      This would be the case for a Tree-RNN or a recursive netwo

In [33]:
class x:
    def __call__(self):
        print('callble')

In [34]:
xx=x()
xx() #class 인스턴스 callable

callble


### closure
- 함수 안에 함수를 정의
- 첫 인자에 따라서 뒤 인자에 영향 줌

In [35]:
def x(m):
    def y(n):
        return m+n
    return y

In [36]:
x(3)

<function __main__.x.<locals>.y(n)>

In [37]:
x(3)(5)

8

- 객체를 closure처럼 사용

In [38]:
class A:
    def __init__(self,m):
        self.m=m
    def __call__(self,n):
        return self.m+n

In [40]:
a=A(3)  #인스턴스해서 초기화

In [41]:
a(5)

8

In [42]:
A(3)(5)

8

정의한 클래스/함수 변경하는 방법 f(g(x))
1. g 자체를 바꿈 
    - 재활용 불가
2. f(h(g(x))): g함수를 바꾸는 추가함수 만듦

### Decorator
- 직접 변경하지 않고 Decorator 로 변경해서 사용

### function decorator
- 함수를 인자로 받는데, 그 인자로 받은 함수를 변경하는 기법

In [48]:
def x(fun):
    ''' 함수를 인자로 받음'''
    print(fun('sun')) #fist class, callble 

In [49]:
x(print) #print('sun')

sun
None


In [50]:
x(len) #len('sun')

3


In [51]:
x(list)#list('sun')

['s', 'u', 'n']


return을 합수로 만들기 위해서 함수를 받음

- `----` 기능 추가

In [53]:
def x(fun):
    def y():
        print('----')
        fun()
        print('----')
    return y

In [54]:
x(print)()

----

----


In [65]:
def dec(fun):
    ''' 2 빼기'''
    def inner(a):
        print('---')
        return fun(a-2)
    return inner

def xx(a):
    ''' 1 더하기'''
    return a+1

In [66]:
dec(xx)(1) # (1+1)-2 =0

---


0

decorator 사용해서 변경 할 수 있도록 만듦
- 재사용 할 수 있도록

In [67]:
@dec
def xx(a):
    return a+1

In [68]:
xx(1)

---


0

In [91]:
def dec(fun):
    def inner(*arg,**kwargs): #인자테크닉
        print('---')
        return fun(*arg,**kwargs)+1
    return inner
@dec
def yy(a,b):
    return a+b+1

In [92]:
yy(1,2)

---


5

### class decorator
- class  에 class decorator 사용
- class 받아서 기능을 바꾸어 줌

In [84]:
from dataclasses import dataclass

In [85]:
@dataclass
class A:
    a: int
    b: str

In [86]:
dir(A)

['__annotations__',
 '__class__',
 '__dataclass_fields__',
 '__dataclass_params__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

In [87]:
x=A(1,'a')

In [88]:
x.a

1

In [89]:
x.b

'a'

> - tf decorator `@tf.function`
    - 인자가 들어가는 경우
    - ()

decorator를 붙이면 원래 이름이 나오지 않음

In [139]:
def dec(fun):
    def inner(*arg,**kwargs):
        print('---')
        return fun(*arg,**kwargs)+1
    return inner

@dec
def xx(a):
    ''' docstring'''
    return a+1

In [140]:
dec

<function __main__.dec(fun)>

현재 파일에 정의한 함수

In [141]:
dec(xx)

<function __main__.dec.<locals>.inner(*arg, **kwargs)>

In [142]:
xx.__name__

'inner'

In [143]:
xx.__doc__

In [144]:
xx.__module__

'__main__'

### functools
함수형 패러다임 3총사 중  한개
### wraps
- waps( function) 의 function의 이름, 정보 체크
- debugging 용이

In [166]:
from functools import wraps,singledispatch

In [133]:
def dec(fun):
    @wraps(fun)
    def inner(*arg,**kwargs):
        print('---')
        return fun(*arg,**kwargs)+1
    return inner

@dec
def xx(a):
    ''' docstring'''
    return a+1

In [134]:
dec

<function __main__.dec(fun)>

In [135]:
dec(xx)

<function __main__.xx(a)>

In [136]:
xx.__name__ #함수 xx

'xx'

In [137]:
xx.__doc__

' docstring'

In [138]:
xx.__module__

'__main__'

-  decorator 인자 받는 경우

In [161]:
def para(n):
    
    def dec(fun):
        @wraps(fun)
        def inner(*arg,**kwargs):
            print('---')
            return fun(*arg,**kwargs)+n
        return inner
    
    return dec

@para(2)
def xx(a):
    ''' docstring: 최종 결과물에 3 더함'''
    return a

In [162]:
xx(2) #함수

---


4

In [163]:
xx(8)

---


10

In [164]:
def para(n=2):
    def dec(fun):
        @wraps(fun)
        def inner(*arg,**kwargs):
            print('---')
            return fun(*arg,**kwargs)+n
        return inner
    return dec

@para()
def xx(a):
    ''' docstring: 최종 결과물에 3 더함'''
    return a

In [165]:
xx(2) 

---


4

decorator 만드는데 decorator 사용

### singledispatch

In [169]:
@singledispatch
def f(x):
    pass

@f.register(int)
def _(x):
    print('int')
    
@f.register(str)
def _(x):
    print('str')

In [170]:
f(3)

int


In [172]:
f('글자')

str


decorator 2개

In [178]:
def b(fun):
    def inner(*arg,**kwargs):
        print('b')
        return fun(*arg,**kwargs)
    return inner

def a(fun):
    def inner(*arg,**kwargs):
        print('a')
        return fun(*arg,**kwargs)
    return inner

In [181]:
@b
@a
def x():
    print('x')

- 실행 순서 x, a, b ->b,a,x
    - b(a(x()))
    - stack 영역에 들어가서 b,a,x
> super

In [182]:
x()

b
a
x


#### higher-order function
 - 함수를 인자로 받거나 함수를 리턴 
 
#### Syntax sugar: 단축 표현

In [183]:
import numpy as np

In [185]:
def xxx(a,b):
    ''' 인자 더하기 '''
    return a+b

In [192]:
x=np.array([1,2])
y=np.array([3,4])

In [193]:
xxx(x,y)

array([4, 6])

In [194]:
xxx([1,2],[4,5])

[1, 2, 4, 5]

In [195]:
yyy=np.vectorize(xxx)
yyy([1,2],[3,4])

array([4, 6])

In [196]:
x+y #벡터합

array([4, 6])

### np.vectorize
- decorator 로 사용할 수 있음

In [197]:
@np.vectorize
def xxx(a,b):
    ''' 인자 더하기 '''
    return a+b

In [198]:
xxx([1,2],[4,5]) #벡터합

array([5, 7])

### 3T
- Technology 기술
- Technique 기법
- Tool 도구
    - 이해하기 위해 3가지 필요 
    
    
    딥러닝에서 가장 많이 쓰는 텐서플로우/파이토치(Tool)을 잘 사용하기 위해 python technique을 배움
    - functional paradigm :데이터를 동시 처리, 이론 실제간의 간극 줄임
        - iterator, generator
            - next()  lazy evaluation
        - map, filter,reduce 

- 파이썬에서는 객체지향, 항수형 패러다임 혼용함


#### Technique
- closure
- `__init__, __call__`
- 문보다 식
- immutable

### 클래스
파이썬 공식문서 자습서의 클래스 참고: https://docs.python.org/ko/3/tutorial/classes.html#a-first-look-at-classes
- 함수/클래스 정의 - 재사용
    - 함수 scope LEGB
    - 클래스 local scope
    
- callable 인스턴스 만들기
- . 접근(attribute 참조)
- 인스턴스화해서 인스턴스 객체로 사용
- 클래스/인스턴스 변수/메서드
    - 인스턴스에 없으면 클래스에서 찾음

In [199]:
class A:
    def x(self):
        print('x')

In [200]:
A.x #function

<function __main__.A.x(self)>

In [201]:
a=A()

In [202]:
a.x #메서드

<bound method A.x of <__main__.A object at 0x7ffae264e210>>

- 함수와 매서드의 개념이 모호함
    - 메서드:첫번째 인자 `self` 생략 
    - 함수: 첫번째 인자 생략 불가
- 파이썬은 모든것이 객체 : 매서드도 객체
- 다중 상속
    - super():메서도 결정 순서 (mro)
- mangling : _class__attribute 로 바뀜
    - descriptor로 비공개 변수 만들기 가능
- class는 외부에서 접근 가능해서 동적으로 추가, 변경,삭제 가능
    - vars()
- iterator, generator 
    - 함수형 +객체지향
- 디자인 패턴: 시스템화에서 사용