# [ICTCOG] 4기 경북대 기본반

- [파이썬 공식문서]https://docs.python.org/ko/3/

## Numpy (2)
- Numerical Python
- array programming
    - 한번에 많은 데이터를- **효율적, 빠르게**처리
        - Python 은 느린 언어(부적합)
        - 속도가 필요한 부분은 C, 비교적 덜 중요하면 Python으로 장점 살림
        - Vectorization 도입
            - Matlab, R, Octave, Python의 Numpy...(행렬,벡터 기반)
        - 편리한 다양한 기능 제공

Numpy Quick Start Tutorial 참고 :  https://numpy.org/doc/stable/user/quickstart.html

In [1]:
import numpy as np

In [3]:
a =np.array([1,2,3]) #homogeneous 

container 나누는 기준
- homogenous vs heterogenous
- sequence vs non-sequence
- mutable vs immutable

In [4]:
dir(a) # __getitem__ -> indexing-> sequence

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [14]:
class A:
    def __index__(self):
        print('index')
        return 1
    def __getitem__(self,other):
        print('getitem')

In [15]:
a=A()
a[0]

getitem


In [16]:
x=[1,2,3]
x[a] #int

index


2

## Array Creation
### np.array
- homogeneous
- sequence
  - 다차원 특성에 맞게 다양한 indexing, slicing 지원
- mutable
    > TensorFlow는 어느정도 numpy 기반
      - tensor :immutable & GPU,TPU 사용 가능

In [18]:
a=np.array([1,2,3])
a[0] #indexing

1

In [19]:
a[:] #slicing

array([1, 2, 3])

`shape`, `dtype` 속성 제일 중요

### np.full
- 동일한 shape을 특정 수로 채움
- `order ='C','F' `

In [25]:
np.full((3,4),2) 

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

### np.zeros
- 0 행렬

In [26]:
np.zeros((3,4)) #0 으로 이루어진 array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.ones
- 1로 이루어진 행렬

In [27]:
np.ones((3,4)) #1 으로 이루어진 array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### np.eye
- 단위 행렬:정방 행렬중 대각선의 원소값은 1 나머지 0

In [29]:
np.eye(3) #

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(3,4) #정방행렬 아닌경우

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [32]:
np.eye(3,4,2) #대각선으로부터 1칸씩 올라감

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [33]:
np.eye(3,4,3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.eye(3,4,4) #0 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.eye(3,4,5) #4이상은 0행렬

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### np.identity
- 단위행렬

In [37]:
b=np.identity(4) #단위행렬(identity matrix/)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- programmer 보다 연구자들이 만들어 깔끔하지 않고 너무 많은 기능을 제공

### np.empty
- C에서 변수 선언만 하고 할당 하지 않으면 메모리의 상태에 따라서 쓰레기 값 들어가 듯이 여기서도 동일
- shape 마다 값들이 상히해지는 것을 알 수 있음

In [42]:
a=np.empty((3,6))
a

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.90091507e-308, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 2.22522053e-306, 1.11261095e-306,
        1.06809792e-306, 1.11261095e-306, 9.34595530e-307]])

In [46]:
a=np.empty((3,3))
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.arange
- array range
- 주어진 값 사이에서 일 정한 간격의 값이 있는 array 리턴

In [52]:
np.arange(10) #range -> array range -> arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.linspace
- 주어진 값 사이에서 일정한 간격을 지정
- 마지막값 포함 여부 지정
- np.linspace(start, stop, num=50,...)
    - start, stop 시작과 끝
    - num : start~stop 사이의 일정한 간격을 통한 값

In [54]:
np.linspace(1,50,10) #1~50의 10개의 값 

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [55]:
np.linspace(1,50,10, endpoint=False)

array([ 1. ,  5.9, 10.8, 15.7, 20.6, 25.5, 30.4, 35.3, 40.2, 45.1])

### np.logspace
- linespace와 비슷하지만 log scale 로 리턴

In [57]:
np.logspace(1,50,10) #로그값으로 등분함

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

## Array 연산
- shape 맞춰야 함
- for 없이도 간단하게 한번에 vectorization으로 빠르게 연산
- **element-wise** operation `+,-.*`

In [68]:
x=np.ones((3,4))
y=np.zeros((3,4))

In [69]:
x+y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
x-y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [71]:
x*y #원소간의 곱셈

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
from math import sin

In [62]:
sin(0)

0.0

In [63]:
sin([0,1,2]) #여러값 한번에 불가

TypeError: must be real number, not list

- 한꺼번에 열개 데이터 처리할때 기존 방식은 하나씩 loop이용해야 해서 비효율적

In [67]:
temp=[]
for i in [0,1,2]:
    sin(i)
    temp.append(sin(i))
temp

[0.0, 0.8414709848078965, 0.9092974268256817]

In [64]:
np.sin([1,2,3]) #loop 없이 동시에 빠르게 연산

array([0.84147098, 0.90929743, 0.14112001])

#### 행렬곱
- 데이터 타입에 따라 연산자가 달라짐
    - np.array :`@` 
    - np.mat :`*,@` 둘 다

In [59]:
a=np.arange(4)
b=np.arange(5,9)
a*b

array([ 0,  6, 14, 24])

- ... 결과값이 너무 커서 생략
    - shape 중요한 이유
- ... 생략해서 출력하는것을 바꿀수 있음

In [58]:
#np.set_printoptions(threshold=sys.maxsize)#print시 어떻게 프린트 할지 옵션 설정

- **기존에 수집된 데이터를 불러와서 처리**할 것이라서 만들 필요가 없음

array programming 에 익숙해져야함
- 기본적 element-wise

In [74]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[1,2]])

In [75]:
a*b #element-wise

array([[1, 4],
       [3, 8]])

In [76]:
a@b #행렬곱

array([[ 3,  6],
       [ 7, 14]])

In [77]:
c=np.mat([[1,2],[3,4]])
c

matrix([[1, 2],
        [3, 4]])

In [79]:
c*c #element-wie 아닌 행렬곱

matrix([[ 7, 10],
        [15, 22]])

In [80]:
c@c  # 행렬곱

matrix([[ 7, 10],
        [15, 22]])

In [82]:
b=0
b+=1 #
b

1

In [83]:
1+1.0 # int+ float => float 

2.0

In [86]:
x=np.array([1,2,3,4])
np.max(x) #numpy

4

In [87]:
x.max()  #method , 첫 인자 생략

4

- function, method
    - mutable 일 경우 자기 자신을 바꾸는 경우 function
    - method는 대응하는 function이 있으나 그 역은 성립 불가

In [88]:
np.append(x,3)
x

array([1, 2, 3, 4])

In [89]:
x.append(3) # 없음

AttributeError: 'numpy.ndarray' object has no attribute 'append'

### ndarray 
- numpy array의 타입
- n 차원 dimension의 array
    - as , from 방식
- 1열로 나열하여 stride indexing
    - Python linked list형태로 데이터 저장
        - C언어 메모리 배열 방식 
            - indexing, slicing 빠름
        - ndarray header 정보에 객체 저장 -> data type(주소, 타입,값 )

### indexing
- [,]
- boolean indexing 
    - 조건을 넣을 수 있음
- fancy indexing [[ ]]
- [()]
- [:]
- 재가공해서 ML,DL 알고리즘에 맞게 재 가공해야 하기 때문에 중요함

In [92]:
a=np.arange(12).reshape(3,4) #shape (3,4)로 변경
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
b=[[1,2],[3,4]]
b

[[1, 2], [3, 4]]

### [][]
- Python indexing
- `[row][col]`

In [102]:
b[1][0] #python indexing

3

In [99]:
a[1][1]

5

### [,]
- `[row, colum]` 

In [100]:
a[1,1]

5

### broadcast 
- 연산에서 자동적으로 크기를 맞춰줌
- 행벡터, 열벡터 1차식인 경우 모양 복사
 

모양이 안맞으면 broadcasting Error

In [104]:
y=np.zeros((3,3))
a+y

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [103]:
a+1 #

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Boolean Indexing
- indexing 에 조건에 따라서 True/False 결과가 나온 값 넣을 수 있음

In [106]:
a>6 #각 원소별 크기 비교

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [107]:
a[a>6] #6보다 큰값 추출 7,8,9,10,11 5개

array([ 7,  8,  9, 10, 11])

In [110]:
a[(a>6) & (a<10)] #복잡한 조건도 넣을 수 있음

array([7, 8, 9])

### fancy indexing
- [[ row,col ]]
- 행별로 원하는 값 추출
    - 행: 하나의 관측치/record
    - 특정 데이터 가져옴

In [114]:
a[[1,0]] #1번째, 0번째 행

array([[4, 5, 6, 7],
       [0, 1, 2, 3]])

In [112]:
a[[0,3]]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [116]:
a[[1,2],[2,3]] #1행 2열 값, 2행3열의 값

array([ 6, 11])

In [117]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
a[[1,2],[2,3]]

array([ 6, 11])

In [119]:
a[(1,2),(2,3)]

array([ 6, 11])

In [121]:
a[0] #0번째 행

array([0, 1, 2, 3])

In [124]:
a[0][:] #상동, [:] 생략 가능

array([0, 1, 2, 3])

In [3]:
from tensorflow.keras.datasets import mnist

In [8]:
(X_train,y_train),(X_test,y_test)=mnist.load_data()

11493376/11490434 [==============================] - 6s 0us/step


In [9]:
X_train  #특정 데이터 뽑아오기

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [10]:
X_train.shape #28x28 이 60,000개

(60000, 28, 28)

In [11]:
X_train[0] #(0,28,28)28x28 0번째 데이터

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [12]:
X_train[0][:][:]  #상동

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [13]:
X_train[0,:,:]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

- Numpy에서 [] 생략 가능



- [N,`:, ... ,:`]
- `,:` 1개 이상인 경우 `...` 로 교체 가능하며 생략도 가능

In [14]:
X_train[0,...]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [131]:
a=np.arange(25).reshape(5,5)

In [127]:
a[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [129]:
b=np.arange(6)
b[::-1]

array([5, 4, 3, 2, 1, 0])

In [130]:
b[::2] #2개씩

array([0, 2, 4])

In [132]:
a[0] #2차원의 열 생략됨

array([0, 1, 2, 3, 4])

In [133]:
a[:,4]

array([ 4,  9, 14, 19, 24])

In [134]:
a[1,3:5]

array([8, 9])

In [136]:
a[3:,3:]

array([[18, 19],
       [23, 24]])

In [138]:
a[2:,::2]

array([[10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

- pandas: 기계학습을 위한 전처리에 초점을 맞출 예정

In [139]:
a[0,1]

1

In [140]:
a[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [143]:
a[[1,2,4],[2,3,4]]

array([ 7, 13, 24])

In [144]:
a[-2:, [0,1,3]]

array([[15, 16, 18],
       [20, 21, 23]])

In [145]:
a[[1,4],[1]]

array([ 6, 21])

In [147]:
b=np.arange(36).reshape(6,6)

In [151]:
b[0,3:5]

array([3, 4])

In [152]:
b[2::2,::2]  #가로 2칸씩 지정

array([[12, 14, 16],
       [24, 26, 28]])

In [153]:

b[4:,4:]

array([[28, 29],
       [34, 35]])

In [154]:
b[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [156]:
b[0,(3,4)]

array([3, 4])

In [159]:
b[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1,  8, 15, 22, 29])

In [160]:
b[3:,[0,2,5]]

array([[18, 20, 23],
       [24, 26, 29],
       [30, 32, 35]])

In [165]:
mask=np.array([1,0,1,0,0,1],dtype=bool)
b[mask,2]

array([ 2, 14, 32])

### Stride
- python linked list(hetero /homo) 계속 데이터 타입 체크 해야하나  Numpy는 데이터 타입 상관 없이 homogeneous 하니깐 내부적으로 **속도 빠르게 접근,연산**
    - 1차원   ( 행,열) 
    - 한 열 넘어가기 위해 필요한 메모리 
    - 한 행 넘어가기위해 필요한 메모리
        > C의 pointer 
        - eg.Uint16= 2byte; shape (3,3) strides (6,2)

In [170]:
c=np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [171]:
c.itemsize

4

In [172]:
c.strides

(12, 4)

In [174]:
d=np.arange(1,9)
d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [176]:
d.dtype #int32 = 4bytes

dtype('int32')

In [175]:
d.strides

(4,)

In [178]:
c.T #order=F인경우

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [179]:
a=np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### axis
- 2차원인 경우 
    - `axis=0` 각 열마다, `axis=1` 각  행마다
    - axis=None 전체
- stride 개념이 숨어 있어 원하는 결과 사용 가능

In [189]:
a.shape #4행 6열

(4, 6)

In [180]:
a.sum() #한 개의 값으로 축약

276

In [181]:
a.sum(axis=0)  # 6개

array([36, 40, 44, 48, 52, 56])

In [183]:
a.sum(axis=1) #4개

array([ 15,  51,  87, 123])

In [186]:
a.min()

0

In [187]:
a.min(axis=0) #각 열마다 최소값

array([0, 1, 2, 3, 4, 5])

In [188]:
a.min(axis=1) #각 행

array([ 0,  6, 12, 18])

In [190]:
a.cumsum(axis=1)

array([[  0,   1,   3,   6,  10,  15],
       [  6,  13,  21,  30,  40,  51],
       [ 12,  25,  39,  54,  70,  87],
       [ 18,  37,  57,  78, 100, 123]], dtype=int32)

In [191]:
np.mean(a,axis=0)

array([ 9., 10., 11., 12., 13., 14.])

In [193]:
np.mean(a,axis=1)

array([ 2.5,  8.5, 14.5, 20.5])

In [194]:
np.mean(a)

11.5

In [195]:
np.lib.stride_tricks #stride 만들 수 있음

<module 'numpy.lib.stride_tricks' from 'C:\\Users\\AI07\\anaconda3\\lib\\site-packages\\numpy\\lib\\stride_tricks.py'>

In [196]:
import numpy.lib.stride_tricks as st

In [197]:
dir(st)

['DummyArray',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_broadcast_arrays_dispatcher',
 '_broadcast_shape',
 '_broadcast_to',
 '_broadcast_to_dispatcher',
 '_maybe_view_as_subclass',
 'absolute_import',
 'array_function_dispatch',
 'as_strided',
 'broadcast_arrays',
 'broadcast_to',
 'division',
 'np',
 'print_function']

### 3차원
2차원 이상의 다차원 공간을 자른다고 생각하면 쉬움
- 각  axis 별로 가려서 보는것 익숙해저야함

In [200]:
d=np.arange(100).reshape(10,2,5)
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [204]:
np.mean(d) #전체

49.5

In [203]:
np.mean(d,axis=0) #(2,5)

array([[45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54.]])

In [201]:
np.mean(d,axis=1)#(10,5)

array([[ 2.5,  3.5,  4.5,  5.5,  6.5],
       [12.5, 13.5, 14.5, 15.5, 16.5],
       [22.5, 23.5, 24.5, 25.5, 26.5],
       [32.5, 33.5, 34.5, 35.5, 36.5],
       [42.5, 43.5, 44.5, 45.5, 46.5],
       [52.5, 53.5, 54.5, 55.5, 56.5],
       [62.5, 63.5, 64.5, 65.5, 66.5],
       [72.5, 73.5, 74.5, 75.5, 76.5],
       [82.5, 83.5, 84.5, 85.5, 86.5],
       [92.5, 93.5, 94.5, 95.5, 96.5]])

In [202]:
np.mean(d,axis=2)#(10,2)

array([[ 2.,  7.],
       [12., 17.],
       [22., 27.],
       [32., 37.],
       [42., 47.],
       [52., 57.],
       [62., 67.],
       [72., 77.],
       [82., 87.],
       [92., 97.]])

### broadcasting
- 모양이 맞지않으면 스칼라,벡터를 다른 고차원 어레이에 복사를 통해 맞춰서 **모양을 맞춤**
- 알아서 맞춤
    - `np.zeros`. `np.ones` 덜 필요해짐

In [205]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [206]:
a+1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [208]:
a+ np.ones(6)

array([[ 0,  2,  4,  6,  8, 10],
       [ 6,  8, 10, 12, 14, 16],
       [12, 14, 16, 18, 20, 22],
       [18, 20, 22, 24, 26, 28]])

In [ ]:
a+np.arange()

행, 열벡터 더하면 메트릭스가됨

In [215]:
np.matrix([0,10,20,30])+np.matrix([0,1,2]).T

matrix([[ 0, 10, 20, 30],
        [ 1, 11, 21, 31],
        [ 2, 12, 22, 32]])

In [ ]:
tf.constant([1,2,3]) +1 # 2,3,4 로 1이 broadcasting 됨

- Less Basic 도 다룸


In [217]:
a= np.arange(4).reshape(1,4)
b=np.arange(4).reshape(4,1)

In [218]:
a+b #서로 브로드 캐스팅해서 (1,4)+(4,1)4x4 됨

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])