# [ICTCOG] 4기 경북대 기본반

- [파이썬 공식문서]https://docs.python.org/ko/3/


* [  함수형 패러다임](#함수형-패러다임)
    * [ 식별자](#식별자)
    * [ 할당](#할당)
    * [ 단순문](#단순문)
* [ Numpy](#Numpy)
    * [ shape](#shape)
    * [ dtype](#dtype)

1. BigData
    - Pandas
    - 정형 데이터 분석
2. **ML**
    - Scikit-learn
3. **DL**
    - TensorFlow 맛보기 

### iterator 
- storage가 아닌 메모리상에 올라간 것이므로 별도의 공간을 확보하지 못함
- 필수 영역으로 올림


- for문도 iterator 로 만들어져서 느림
가상메모리가 확장되야하는데 느림
메모리 전체를 필수영역에 올리지않고 하나씩 올림
- C 처럼 메모리를 건들 수 없음.


## 함수형 패러다임

> - TensorFlow: 흑인 공동체를 위한 인종적 평등을 추구하기 위해 노력하고 있습니다.
     - boston 집값 예측 데이터에 흑인 거주자 인구에 대한 데이터 뺌.

        
## descriptor
- 접근 제한
- descriptor 3가지 방식
    1. compositoin
    2. property 객체이용 get,set,del method
    3. decorator 

### 연산자 오버로딩
- 연산자를 재정의하여 바꿈
- 연산자와 연결된 매직메소드로 오버라이딩 해서 연산자 오버로딩을 함
    > 오버라이딩 vs 오버로딩
        - 파이썬에서는 경계가 희미
    - eg. C++ 연산자 오버로딩
`<<` `__lshift__`

### decorator
- `@classmethod, @staticmethod, @property,@class.setter  `

#### @staticmethod
- `self`,`cls` 와 같이 클래스, 인스턴스 자체를 가리키는 메소드가 없음
- class 이름 namespace에서 쓰는 함수처럼 사용
- class, instance 관련없고 class의 namespace 빌려옴
- `@staticmethod`: 정적인 메소드
- instance, class 모두 접근 가능

- *arg 함수 정의:가변 포지셔널  , 함수 호출: 
- generator : yield

### dispatch
- generic function 만드는 방식
- 오버로딩과 비슷
- 타입에 따라서 오버로딩을 지원하는것과 비슷(내부적으로 다르게 처리)

#### singledispatch
- 데이터 한 개가 들어왔을때
- python에서는 기본적으로 single dispatch 지원하고 그 이상은 추가 모듈 설치
> - double dispatch: 데이터가 2개 들어오는 경우
> - multiple dispatch: 2개 이상

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

- 인자 1개

In [1]:
len({1,2,3})

3

In [2]:
len('abcd')

4

In [3]:
from functools import singledispatch

### property
- `@property`
- **callable이 callabe 아닌것으로 변경되어 () 안 붙여도 됨**
>  callable `()` 붙일 수 있음
   - 클래스, 함수, 클래스 내 `__call__` 정의된 경우 인스턴스
- 코드 간결성 보장함

In [4]:
class A:
    def __init__(self,x):
        self.x=x
    @property
    def y(self):
        return self.x

In [5]:
a=A(3)

In [6]:
a.y

3

### multiple dispatch
- 오버로딩
- 이름은 동일하지만 데이터 타입마다 다름
- LBYL (돌다리도 두들겨보고 건너기) 방식으로 해야함.

- delegation(위임)
    - 파이썬: 부모로 위임

#### Lazy Evaluation
- iterator, generaotr의 `next`: 하나씩 차례로 가져옴
- `__getitem__` : indexing, sliciing 가능
- abc :Abstract base class(추상 클래스)
    - 상속받아 사용
    - 실제 구현 안하면 NotIementedError

- `__next__` -> iterator만 next 사용하나 덕타이핑 방식으로 iterable로 상속받아 추가하면 iterator처럼 사용 가능
- duck-typing: 오리처럼 울면 오리로 간주함

- Python 상속체계를 따르지 않아도 duck-typing 제공
- 특별한 기능을 정의하면 부모객체 처럼

In [8]:
import collections.abc

#### 상속
- 실무에서는 자주 사용하지 않음
- 다중상속은 부모객체의 **강하게 연결**되어 부모 객체가 바뀌면 자식객체도 바뀔 수 있음
- 유지보수 어려움

상속 없이 하는 2가지
1. composition 
     - 상속받지않음
2. duck-typing 추가(python에서 지원)
    - 약간만 필요한 경우
    
### higher-order functions
- 고차함수 : 함수를 인자로 받을 수 있거나 또는 함수를 리턴함
    - map, filter, reduce 삼총사
    - accumulation vs reduce 
        - accumulation 중간 결과값 저장
        - reduce 한개의 결과값으로 축약하여 최종값 만 리턴
         
    - first class fucntion: 파이썬에서는 함수가 객체

--- 
- paradigm :
1. 명령형(지시에 맞게 실행)
   - 절차적
   - 객체지향
       - Array Programming: array라는 데이터 타입을 갖고 프로그래밍
           - e.g Matlab: array는 데이터 타입의 일종
           - LISP(List Programming)
           - 빅데이터, 인공지능 등의 데이터 기반에서의 기초
           - array: homogeneous n-dimensional matrix
           - 예. 이미지 3차원 행렬( 높이, 넒이, 채널)
           - 엑셀도 array 
           - 데이터 기반 프로그램들은 데이터 하나ㅎ나 처리하는데 관심없음
           -  선형대수와 관련되 데이터를 동시에 처리하는것에 관심이 있음
               - functional paradigm
           - Python, PyTorch defacto 라이브러리
2. 선언형(기존에 있는것을 조합)
    - 함수형패러다임(수학함수 이용)
    
### import
- 파일 생성

In [9]:
import numpy as np

In [14]:
x=1
_x=2
def y():
    return 1
def _y():
    return 2

In [11]:
import sys
sys.path

['C:\\Users\\AI07',
 'C:\\Users\\AI07\\anaconda3\\python38.zip',
 'C:\\Users\\AI07\\anaconda3\\DLLs',
 'C:\\Users\\AI07\\anaconda3\\lib',
 'C:\\Users\\AI07\\anaconda3',
 '',
 'C:\\Users\\AI07\\AppData\\Roaming\\Python\\Python38\\site-packages',
 'C:\\Users\\AI07\\anaconda3\\lib\\site-packages',
 'C:\\Users\\AI07\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\AI07\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\AI07\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\AI07\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\AI07\\.ipython']

In [1]:
import folder.temp as temp #temp.py 파일만 가져옴
dir(temp)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_x',
 '_y',
 'x',
 'y']

In [2]:
temp._x

2

In [3]:
%whos

Variable   Type      Data/Info
------------------------------
temp       module    <module 'folder.temp' fro<...>\\AI07\\folder\\temp.py'>


In [6]:
from temp import _x #파일에서 _x를 내 namesapce로 가져옴

ModuleNotFoundError: No module named 'temp'

In [5]:
%whos

Variable   Type      Data/Info
------------------------------
temp       module    <module 'folder.temp' fro<...>\\AI07\\folder\\temp.py'>


In [ ]:
dir(foler)

In [19]:
_x

2

In [33]:
from temp import * #namespace에 _ 제외하고 모든 것을 가져옴

In [34]:
%whos

Variable         Type        Data/Info
--------------------------------------
A                type        <class '__main__.A'>
a                A           <__main__.A object at 0x000002C4B34E0AF0>
collections      module      <module 'collections' fro<...>ollections\\__init__.py'>
folder           module      <module 'folder' (namespace)>
ft               module      <module 'folder.temp' fro<...>\\AI07\\folder\\temp.py'>
np               module      <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
singledispatch   function    <function singledispatch at 0x000002C4AFBAA820>
sys              module      <module 'sys' (built-in)>
temp             module      <module 'folder.temp' fro<...>\\AI07\\folder\\temp.py'>
x                int         1
y                function    <function y at 0x000002C4B35464C0>


파일 또는 폴더를 namespace로 가져옴

In [35]:
ft.__name__

'folder.temp'

- __@ : mangling, 클래스의 변수 이름을 바꿈 _class__이름
- _@  : imprt * 에서 못 가져옴

folder 구조
- 복잡한 형식으로 py 파일을 가져옴

In [26]:
import folder.temp as ft #binding

In [27]:
%whos

Variable         Type        Data/Info
--------------------------------------
A                type        <class '__main__.A'>
a                A           <__main__.A object at 0x000002C4B34E0AF0>
collections      module      <module 'collections' fro<...>ollections\\__init__.py'>
ft               module      <module 'folder.temp' fro<...>\\AI07\\folder\\temp.py'>
np               module      <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
singledispatch   function    <function singledispatch at 0x000002C4AFBAA820>
sys              module      <module 'sys' (built-in)>
x                int         1
y                function    <function y at 0x000002C4B35464C0>


global 영역에 들어와야함.

### packaging 

In [8]:
import numpy

In [9]:
dir(numpy)# __file__

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [10]:
import numpy as np

---
## Numpy

#help > Numpy Reference ( Numpy 공식문서 참고)
- https://numpy.org/doc/stable/index.html
- 다룰 데이터가 array 형태로 되어있어 최적화된 패키지
- 기본 설치되어있음

### Array Programming
- ND Array : homogeneous 한 데이터 스트럭쳐
    - 0차원 Scalar
    - 1차원 Vector
    - 2차원 Matrix / DataFrame(table)/ 3d Array/Tensor
    - 3차원 Array
    - 4차원 큐브 벡터, 5차원 큐브 매트릭스
    
 > 머신러닝 
    - functional pradigm 동시 처리
    - Numpy : array programming에 필요한 기능 다 지원
    
  > [Numpy for Matlab users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)
    - Matlab 상용(특정 목적으로 확장이 한정적, 비쌈) -> Octave 오픈 소스
    - Travis Oliphant 
        - Matlab 을 Python에서 사용하도록 만듦
        - slicing 이 카피하지 않음(메모리 공유하지 않음)
        - 다양한 데이터 타입

> Matplotlib : Matlab 그대로 가져옴

- Python의 느린 속도 

1. GPGPU(general purpose GPU), **Multi-processor**, parallel computing: 복잡한 연산량
2. Compiler language 
    - CPython, PyPy (JIT 순간순간 컴파일해서 속도 향상)
    - 호환성의 문제
3. **Glue Lauguage 특성 ** 풀처럼 다른 언어와 잘 붙음
    - 언어이자 명세서:https://docs.python.org/ko/3/reference/introduction.html#alternate-implementations
        - CPython(C, 기본), Jython (JAVA), PyPy
        - 속도가 필요한 부분은 C, 나머지 Python       
4. Algorithm/ Data Structure

### Vectorization
- Multi-core 활용
    - QuadCore 는 4개 **동시에(batch operation)**  CPU 가 **loop 없이** 계산
    - for 사용하지 않음 -> 함수형패러다임 for 없음
- 속도 빠른 이유 vectorization, 일부는 C로 내부적으로 만들어짐
- Python에서 tensorflow와 같이 복잡한 연산 할 수있게 된 기여(1970년도)

In [11]:
import numpy as np #np라는 네임스페이스

array n 차원 구조

#### factory method
- design patter중 하나
- 객체 만들때 인스턴스화 `클래스()` 말고 클래스 이름으로 생성하는대신 다른 메소드로 생성 클래스를 생성하는 다른 방법

In [13]:
a=np.array([1,2,3]) #class 아닌 함수
a

array([1, 2, 3])

In [14]:
a=np.array([1,"2",3]) # 모두 문자열로 바뀜
a

array(['1', '2', '3'], dtype='<U11')

In [15]:
a=np.array([1,2.,3]) # 모두 float으로 바뀜
a

array([1., 2., 3.])

In [16]:
import array #파이썬 기본

### np.array
- 행렬 , matrix 연산을 안 함
- numpy 수학적 array, array 자료구조의 array
    - homogeneous
    - sequence 더하면 추가됨
- np.array는 array 연산(element-wise)
-  `numpy.ndarray`  type

In [19]:
a=np.array([1,2.,3])  #요소 갯수 맞춤
b=np.array([2,3, 4])
a+b   #int + float -> float

array([3., 5., 7.])

In [20]:
a=np.array([1,2.,3])  #float 
b=2
a+b

array([3., 4., 5.])

In [21]:
type(a) #type : numpy.ndarray 

numpy.ndarray

- `__repr__` :array([3., 4., 5.])
- `__str__`: [1. 2. 3.]
    - 이름과, print 한 경우가 상이

In [23]:
print(a) 

[1. 2. 3.]


#### ndarray 
- shape 정의해서 array 생성

In [25]:
b=np.ndarray([1,2,3]) #shape 정의해서 array 생성
b

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
b.shape

(1, 2, 3)

Numpy에서 중요한 2가지
- `shape`: array 모양
- `dtype`: homogeneous array의 데이터 타입(연산 값 달라짐)

#### shape
- array 모양
    - 1차원 원소 갯수 (n,)
    - 2차원   (m,n)
    - 3차원(k,l,m)
- 각 [] 쌍을 하나씩 제거 해서 shape 맞춤
- 행렬 연산에서 shape 중요함

In [28]:
a.shape #

(3,)

In [31]:
b=np.array([[1,2],[3,4]])
b.shape

(2, 2)

In [33]:
c=np.array([[[1,2,3],[4,5,6]]])
c

array([[[1, 2, 3],
        [4, 5, 6]]])

In [34]:
c.shape

(1, 2, 3)

#### dtype
- numpy는 내부적으로 C로 만들어져서 C,Python 자료 타입이 있음
    - int32,float32 ...
- 많은 데이터 타입을 지원하지만 목적에 따라  몇가지의 데이터형만 사용할 예정 `Uint8`..
- 데이터타입 만들 수 있음 (데이터 처리 pandas 중요)

In [35]:
c.dtype #int32 

dtype('int32')

In [ ]:
from tensorflow.keras.datasets import mnist

In [ ]:
(X_train, y_train),(X_test, y_test)=mnist.load_data() #unpacking

In [ ]:
X_train #데이터가 크면 ... 생략되어 알 수가 없음

In [ ]:
X_train.shape #60,000개의 28x28 크기의 행렬(이미지) 있음

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(X_train[0])

- matrix 기반
- 각 2차원인 matrix 별로 공백이 있음(Matlab 영향)
    - (k,l,m) : lxm행렬 k개
    - **공간에 대한 이해**가 필요
- 행렬 연산에서 shape 기반

In [40]:
a=np.zeros((4,3,2))# 3x2 행렬 4개
a # [] 하쌍 씩 소거해서 4,3,2

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [39]:
print('shape:',a.shape,)

shape: (4, 3, 2)


In [42]:
a.dtype #float64  0.

dtype('float64')

In [49]:
b=np.arange(24).reshape(4,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [45]:
b.dtype

dtype('int32')

In [46]:
b.shape

(4, 6)

Array programming 으로 **값 동시에 연산하는** 것이 의미가 있음(예. 피보나치- array 연산)
- 수학적 점화식 

In [51]:
a=np.array([[1,1],[1,0]])
a

array([[1, 1],
       [1, 0]])

In [52]:
a*a #제곱

array([[1, 1],
       [1, 0]])

In [53]:
a**5 #5승

array([[1, 1],
       [1, 0]], dtype=int32)

In [54]:
a@a

array([[2, 1],
       [1, 1]])

In [55]:
a@a@a@a@a

array([[8, 5],
       [5, 3]])

- shape, dtype 으로 대부분을 유추 가능

In [64]:
#2행 3열
a= np.array([[1.,0,0],[0,1,2]])
a

array([[1., 0., 0.],
       [0., 1., 2.]])

In [65]:
a.shape #2차원 (2행 3열) , 

(2, 3)

In [66]:
a.ndim #2 차원 

2

In [67]:
a.size #6개의 원소

6

In [68]:
a.dtype #시스템마다 다름  64bits= 8byte

dtype('float64')

In [69]:
a.itemsize  #8 byte

8

### Array Creation
- factory method 로 하나씩 만드는 것은 힘들기 때문에 규칙에 따라서 만들 수 있음
> - range, 함수형 패러다임 
> - comprhension (list,dict, set comp) 
    - tuple comp는 generator expressoin

### np.zeros
- 0으로 이루어진 행렬에 shape 지정
- `zeros(shape, dtype=float, order='C')`
    - order: C 좌우, F(Fortran) 상하
        - C 기반
    - 메모리는 1차원 구조, stride이용해서 차원 표기

In [70]:
a=0

In [71]:
a=np.zeros((3,4)) #shape(3,4)

### np.zeros_like
- `np.zeros_like(a, dtype=None, order='K', subok=True, shape=None)`
- 행렬 크기만큼 0 으로 이루어진 행렬로 만들어줌

In [73]:
b=np.zeros_like(a)
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])