# [ICTCOG] 4기 경북대 기본반


## Numpy (3)

- array programming:  **vectorization**으로 여러 elements 의 동일한 계산하는것을 동시에 실행하여 속도 효율적

### 변환
- 데이터 처리를 생성보다는 기존에 만들어진 것을 가져와서 목적에 맞게 변형하는 경우가 많아  연산을 위해서 모양 바꾸는게 중요

#### from 
- 완전히 다른 데이터 타입으로 바꿈

#### as
- 작은 범위의 데이터 바꿈

> - function에는 있지만 method에 없는 경우 있음 

In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3]) 
x

array([1, 2, 3])

##### astype
-  method 방식 type casting (C기반)
- 원하는 데이터 타입으로 변경

In [4]:
c=a.astype('float')
c

array([1., 2., 3.])

##### np.asfarray
- float type의 array로 변경

In [5]:
a=np.asfarray(x)  #function 방식
a

array([1., 2., 3.])

- `shape`, `dtype`

- broadcasting 
    - 행렬연산 시에 알아서 shape 맞춰줌
- 상수, 행/열 벡터인 경우 경우에 따라서 broadcasting
- 빠르고 쉬움 (de facto)

#### Numpy 단점
- Numpy는 미묘한 차이로 다양한 기능을 너무 많이 제공
    - 예. eye, identity
- GPU 사용 불가
- mutable
    - 비추천
    
#### np.broadcast
- broadcasting을 흉내내는 객체

In [48]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
list(b)

[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]

### ufunc
- [universal function](https://numpy.org/doc/stable/reference/ufuncs.html?highlight=universal%20function)
    - `numpy.ufunc`
- **차원, 타입에 상관없이 element-wise, vectorizaed array opration** 가능
- 내부적으로 vectorization 되어 있어 빠름
    - `all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where`

In [18]:
type(np.sum)

function

In [22]:
type(np.sum)#상속받은게 아님!

function

In [21]:
type(np.sum).__bases__  

(object,)

In [23]:
sum([1,2,3,4,5])   

15

In [25]:
sum(1)#iterable 만 가능

TypeError: 'int' object is not iterable

In [24]:
np.sum(1)

1

In [26]:
np.sum([1,2,3,])

6

In [27]:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [29]:
a=np.arange(12).reshape(3,4)
for i in a: #각 행 추출
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


- Numpy array
    - homogeneous: 빠른 속도
    - sequence: indexing, slicing 지원(5가지)        
    - mutable
        - 동일한 주소값을 공유해서 같이 변경됨
        - 해결책: copy
    - iterable ( `__iter__`,` __next__` 있어 for 문에 넣을 수 있음)

In [45]:
a=np.array([1,2,3]) #mutable 로 인해 메모리 번지가동일하게 가리킴
b=a
b[1]=100
a

[1, 100, 3, 4]

### Review
attribute: class에 정의된 method,variables 통칭
- broadcast : 알아서 shape 맞춰줌
- C ordr : row-major( 행 기반)
- F 0rder: col-major
- flattened
- iteralbe 
 참고: glossaryhttps://numpy.org/doc/stable/glossary.html

### Copy
- mutable 타입에서도 값 변하지 않고 복사(copy) 가능하도록 함
- **Numpy Copy는 Python의 Copy와 다르므로 주의**
- shallow, deep copy 구분

|       |shallow  | deep        |
|-------|---------|-------------|
|Python | copy,[:]|copy.deepcopy|
|Numpy  |         | **copy**   |

#### Python Copy
- mutable 인 경우 같이 바뀌는 경우 존재
    - shallow :2차원 이상인 경우 mutable로 인해 변경됨
        - `copy()`, `[:]`
    - deep:2차원 이상까지 copy 
        - `copy.deepcopy()`

In [56]:
#1차원 list
d=[1,2,3]
e=d.copy()
e[0]=100
d

[1, 2, 3]

In [60]:
f=d[:]
d.append(1)
f

[1, 2, 3]

In [57]:
#2차원 list
a=b=[[1,2],[3,4]]
b=a.copy()
b[0][0]=100
a  #바뀜!

[[100, 2], [3, 4]]

In [61]:
import copy

In [64]:
a=[[1,2],[3,4]]
bb=copy.deepcopy(a)
bb[0][0]=100
a

[[1, 2], [3, 4]]

#### Numpy Copy
- Numpy는 예외사항
    - deep
        - `copy()`
            - python에서는 shallow copy, Numpy에서는 deep copy

In [67]:
xx=np.array([[1,2,],[3,4]])
yy=xx.copy()
xx[0][0]=100
yy #2차원 이상이지만 Numpy 에서는 deep copy

array([[1, 2],
       [3, 4]])

#### view
- 동일한 id /메모리 값 동일함( 메모리 공유)

> - view vs copy
    - copy는 메모리 번지 새롭게 만들어 바뀌는거 방지
    - view는 동일한 메모리 번지 가리켜서 같이 바뀜

In [73]:
x=np.array([1,2,3])
id(x)

1891606203248

In [75]:
y=x
id(y) # id 가 동일하므로 copy가 아님 

1891606203248

In [76]:
z=x.view()
id(z)

1891606203888

In [69]:
zz=yy.view()
yy[0][0]=100
zz

array([[100,   2],
       [  3,   4]])

In [70]:
xxx=np.array([1,2,3]) #python에서는 copy 아님
zzz=xxx.view()   
zzz[0]=100
xxx  #값이 변함

array([100,   2,   3])

데이터 포맷이 파이썬, Numpy 중 무엇인지 확인


In [78]:
c=np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
d=c[:,1]
d

array([100,   5,   9])

In [85]:
d[0]=100 
c       # view: indexing, slicing은 copy 아님

array([[100, 100, 100, 100],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

#### \_\_base__
- Numpy 의 `__base__`
    - copy: return None
    - view 공유하고 있는 결과 return
- 중간중간에 copy해서 checkpoint 만들어둠

In [92]:
c=np.arange(12).reshape(3,4)
d=c[[0]] #fancy indexing
d[0][0]=100
c  # copy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
d.base  #copy 인 경우 None

In [95]:
d=c[:,1]
d.base  #view 인 경우 공유하고 있는 out return

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Pytmhon 의 `__base__`
- 부모 객체

In [103]:
class X:
    pass
x=X()
X.__bases__  #class 의 부모 객체들

(object,)

In [104]:
X.__base__  #class의 부모 객체 1개

object

In [111]:
c.flat #option 없음

세분화 시켜서 할 수 있음

In [115]:
np.nditer(c,order='K')

In [114]:
for i in np.nditer(c,order='F'): #열 기준
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [116]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

python 관점에서 array 구조가 어떠한 성질을 갖는지 보았음
### shape manipulation
- reshape
- flatten, revel

#### reshape
> - broadcasting: 모양 알아서 맞춰줌
- array를 동일한 원소크기 내에서 모양 변경
- `a.reshape(shape, order='C')`
    - shape (r,c) or r,c 
    - reshape((r, -1 )): size 내에서shape 맞춤
        - -1 외에 다른 음수값 가능
> mutable return 3가지
 1.자기자신 변함(in place), return 없음
     - `append()`
 2.자기자신 변함(in place), return 
     - `pop()`
 3.자기자신 무변, return 없음

In [119]:
a=np.arange(24)  #원소갯수 24개
a.reshape((4,6)) #4x6 array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [129]:
a.reshape(2,5) #원소 갯수가 동일해야함

ValueError: cannot reshape array of size 24 into shape (2,5)

In [120]:
a.reshape(4,6) #mutable 처럼 안 바뀜

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [131]:
a.reshape(4,-1) #자동으로 size 내에서 reshape 함

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [132]:
a.reshape(4,-1000) 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [122]:
a=a.reshape(4,6)

In [126]:
b=[1,2,3]
b=b.append(4) # return None -> b = None 

In [128]:
b.append(4)

#### resize
-  원소 갯수 
    - `reshape`: return 있으나 무변
    - `resize`: return 없으나 변하므로 주의

In [6]:
import numpy as np
a=np.arange(24).reshape(4,6)
a.size

24

In [7]:
a.resize(4,6)  #return 이 없음

In [8]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

- size 가 큰경우 zero-padding (뒤에서 0으로 채움)
- size 가 작은 경우 뒤에서 부터 자름

In [31]:
b = np.array([[0, 1], [2, 3]])
b.resize(2, 1)
b

array([[0],
       [1]])

In [32]:
b.resize(3,3, refcheck=False) #zero-padding으로 나머지 0으로 채움
b

array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
np.resize(a,(3,4)) #function -> 더 안전

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### 1차원화

#### flatten
- flatten
    - copy
        - flatten 이 더 안전
        
#### ravel
- raVel (V) 
    - View (Ravel의 Bolero 볼레로 ... 뷰)

In [33]:
a.flatten()  #copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### flat
- Flat iterator 객체는 array를 1차식으로 바꾸어줌
    - type: numpy.flat**ifier** class의 객체
    
    > -  `dir`,`type`, `vars` 가장 중요한 3가지
            - `type(class)` => type
            - `type(instance)`=>class

In [31]:
a.flat #<numpy.flatiter

In [38]:
type(a.flat) #instance

numpy.flatiter

In [40]:
type(np.flatiter) #class  

type

In [32]:
dir(a.flat) #__next__,__iter__

['__array__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'base',
 'coords',
 'copy',
 'index']

In [34]:
for i in a.flat:
    ''' 1차식으로 출력''' 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### stacking
- 특징을 외워서 상황에 맞추어 사용 (차원 추가 여부, axis)
    - `tile, repeat , append, concatenate, hsatck, vstack`
    - `stack, dstack` 차원추가 
#### np.tile
- array를 주어진 숫자만큼 복사해서 반복해서stacking

In [153]:
np.tile(a,2)

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23]])

In [154]:
np.tile(a,(1,2))

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23]])

In [155]:
np.tile(a,(2,1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

#### np.repeat
- array의 각 원소를 반복

In [157]:
np.repeat(a,3)

array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,
        5,  6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11,
       11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16,
       17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22,
       22, 23, 23, 23])

#### np.append
- array의 끝에 지정한 원소 붙임
- axis에 따라서 지정 가능
    - `axis=0`:열 결합
    - `axis=1`:행 결합
        - axis 마다 동일해야 결합 가능
- `axis=None` 지정 안한경우 1차원으로 appending
    - 각 array의 크기와 상관없이 합침


In [158]:
np.append(a,4) #

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  4])

In [159]:
np.append(a,a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [160]:
a=[1,2,3]
a.append(a)
a  #자기자신을 appending 하면 python 에서는 [...]

[1, 2, 3, [...]]

In [162]:
a=np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [164]:
np.append(a,a,axis=1) # row binding 

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23]])

In [165]:
np.append(a,a,axis=0)#col binding

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [166]:
np.append(a,a) #

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### concatenate
- append 와 유사하나 axis=0 기본값

In [169]:
np.concatenate((a,a))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [174]:
np.concatenate((a,a),axis=None)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [171]:
np.concatenate((a,a),axis=1)

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23]])

In [172]:
np.concatenate((a,a),axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [175]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [177]:
np.append(a,b) #axis=None 기본이라서 크기라 달라도 가능

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11])

In [179]:
np.append(a,b,axis=0)  #shape 안 맞아서 error

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 1 has size 3

In [183]:
np.concatenate((a,b),axis=None)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11])

In [184]:
np.concatenate((a,b),axis=0)#shape 안 맞아서 error

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 1 has size 3

In [185]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2],
       [ 6,  7,  8,  9, 10, 11,  3,  4,  5],
       [12, 13, 14, 15, 16, 17,  6,  7,  8],
       [18, 19, 20, 21, 22, 23,  9, 10, 11]])

In [186]:
a.shape

(4, 6)

In [187]:
b.shape

(4, 3)

### np.stack
- 차원이 추가됨
- stacking 했을때 행렬 사이에 공간으로 구분
- `np.stack(arrays, axis=0, out=None)`

In [190]:
np.stack((a,a)) #3차원  shape : (2,4,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [191]:
np.stack((a,a),axis=1) #  (4,2,6 )

array([[[ 0,  1,  2,  3,  4,  5],
        [ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [18, 19, 20, 21, 22, 23]]])

In [192]:
np.stack((a,a),axis=2)# (4,6,2)

array([[[ 0,  0],
        [ 1,  1],
        [ 2,  2],
        [ 3,  3],
        [ 4,  4],
        [ 5,  5]],

       [[ 6,  6],
        [ 7,  7],
        [ 8,  8],
        [ 9,  9],
        [10, 10],
        [11, 11]],

       [[12, 12],
        [13, 13],
        [14, 14],
        [15, 15],
        [16, 16],
        [17, 17]],

       [[18, 18],
        [19, 19],
        [20, 20],
        [21, 21],
        [22, 22],
        [23, 23]]])

#### np.hstack
- horizontal stacking

In [194]:
np.hstack((a,a))

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23]])

#### np.vstack
- vertical stacking

In [195]:
np.vstack((a,a))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

#### np.dstack
- depth stacking 차원 추가

In [196]:
np.dstack((a,a))

array([[[ 0,  0],
        [ 1,  1],
        [ 2,  2],
        [ 3,  3],
        [ 4,  4],
        [ 5,  5]],

       [[ 6,  6],
        [ 7,  7],
        [ 8,  8],
        [ 9,  9],
        [10, 10],
        [11, 11]],

       [[12, 12],
        [13, 13],
        [14, 14],
        [15, 15],
        [16, 16],
        [17, 17]],

       [[18, 18],
        [19, 19],
        [20, 20],
        [21, 21],
        [22, 22],
        [23, 23]]])