# [ICTCOG] 4기 경북대 기본반

## Pandas (1)
### pandas
- 정형데이터 통계적 분석, EDA, **기계학습을 위한 전처리 
    - 분석은 다루지 않을 예정
- Numpy 기반


- 한국철도시설공단 철도종합시험 정보:  https://www.data.go.kr/data/15020859/fileData.do

### read_csv
- 특정형태의 데이터를 pandas DataFrame으로 불러옴
    - 파일 3 요소 : 경로,이름, 확장자 `경로/이름.확장자`
        - 동일한 경로이면 생략 가능
        - encoding 한글 cp959 ,EUC-KR

In [1]:
import numpy as np
import pandas as pd #같이 사용하니 같이 import

In [12]:
data=pd.read_csv('tt.csv','cp949')  #UnicodeDecodeError    -> encoding
data

<ipython-input-12-d35268d5671e>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  data=pd.read_csv('tt.csv','cp949')  #UnicodeDecodeError    -> encoding


사업명,사전점검 시작일자, 사전점검 종료일자,영업시운전 시작일자,영업시운전 종료일자,시설물검증시험 시작일자,시설물검증시험 종료일자
0   호남권내륙화물기지 인입철도,2005-03-10,2005-03-10,2005-03-1...                      
1   동부전동차사무소건설(기지 턴키공사),2005-04-06,2005-04-08,2005...                      
2   조치원~대구 전철화,2005-04-26,2005-04-29,2005-04-27,20...                      
3   대구선철도이설(동대구~청천),2005-10-05,2005-10-07,2005-10-...                      
4   청량리-덕소 복선전철(중앙선),2005-11-21,2005-11-23,2005-11...                      
..                                                ...                      
78  인천공항 제2역개 터미널 연결,2017-07-12,2017-07-14,2017-11...                      
79  포항~삼척 철도건설,2017-07-18,2017-07-26,2017-10-25,20...                      
80  인천공항철도 마곡역 신설사업,2018-07-04,2018-07-05,2018-09-...                      
81  원주~강릉 철도건설,2018-03-05,2018-03-06,2018-05-24,20...                      
82  호남고속철도 2단계 건설사업,2019-01-21,2019-01-24,2019-03-...                      

[83 rows x 1 columns]

In [9]:
data=pd.read_csv('tt.csv',encoding='EUC-KR') #factory method 
data

사업명   사전점검 시작일자   사전점검 종료일자  영업시운전 시작일자  영업시운전 종료일자  \
0        호남권내륙화물기지 인입철도  2005-03-10  2005-03-10  2005-03-11  2005-03-11   
1   동부전동차사무소건설(기지 턴키공사)  2005-04-06  2005-04-08  2005-04-07  2005-04-07   
2            조치원~대구 전철화  2005-04-26  2005-04-29  2005-04-27  2005-04-28   
3       대구선철도이설(동대구~청천)  2005-10-05  2005-10-07  2005-10-07  2005-10-07   
4      청량리-덕소 복선전철(중앙선)  2005-11-21  2005-11-23  2005-11-22  2005-11-23   
..                  ...         ...         ...         ...         ...   
78     인천공항 제2역개 터미널 연결  2017-07-12  2017-07-14  2017-11-20  2017-11-29   
79           포항~삼척 철도건설  2017-07-18  2017-07-26  2017-10-25  2017-12-19   
80      인천공항철도 마곡역 신설사업  2018-07-04  2018-07-05  2018-09-04  2018-09-10   
81           원주~강릉 철도건설  2018-03-05  2018-03-06  2018-05-24  2018-05-27   
82      호남고속철도 2단계 건설사업  2019-01-21  2019-01-24  2019-03-19  2019-05-24   

   시설물검증시험 시작일자 시설물검증시험 종료일자  
0    2005-03-11   2005-03-11  
1    2006-04-18   2005-04-19  
2    2005-05-19   2005-05-26  
3    2005-10-10   2005-10-10  
4    2005-11-25   2005-11-25  
..          ...          ...  
78   2017-09-25   2017-11-08  
79   2017-08-30   2017-09-13  
80   2018-08-08   2018-08-23  
81   2018-05-02   2018-05-03  
82   2019-03-19   2019-05-24  

[83 rows x 7 columns]

상권정보 : https://www.data.go.kr/tcs/dss/selectFileDataDetailView.do?publicDataPk=15012005

In [2]:
data= pd.read_csv('shop/a.csv',sep='|') #빠르게 처리

In [3]:
data

상가업소번호            상호명         지점명 상권업종대분류코드  상권업종대분류명 상권업종중분류코드  \
0       19905471         와라와라호프         NaN         Q        음식       Q09   
1       19911397  커피빈코리아선릉로93길점  코리아선릉로93길점         Q        음식       Q12   
2       19911801           프로포즈         NaN         Q        음식       Q09   
3       19912201       싱싱커피&토스트         NaN         Q        음식       Q07   
4       19932756       가락사우나내스낵         NaN         F     생활서비스       F09   
...          ...            ...         ...       ...       ...       ...   
573675  16394290        비파티세리공덕         NaN         Q        음식       Q01   
573676  16336474          앤탑PC방         NaN         N  관광/여가/오락       N01   
573677  16336218       오즈아레나PC방         NaN         N  관광/여가/오락       N01   
573678  16335152         파인트리네일         NaN         F     생활서비스       F01   
573679  16335150         마이리틀네일         NaN         F     생활서비스       F01   

            상권업종중분류명 상권업종소분류코드     상권업종소분류명 표준산업분류코드  ...  \
0               유흥주점    Q09A01        호프/맥주   I56219  ...   
1             커피점/카페    Q12A01  커피전문점/카페/다방   I56220  ...   
2               유흥주점    Q09A01        호프/맥주   I56219  ...   
3              패스트푸드    Q07A10        토스트전문   I56192  ...   
4           대중목욕탕/휴게    F09A02   사우나/증기탕/온천   S96121  ...   
...              ...       ...          ...      ...  ...   
573675            한식    Q01A01    한식/백반/한정식   I56111  ...   
573676  PC/오락/당구/볼링등    N01A01       인터넷PC방   R91222  ...   
573677  PC/오락/당구/볼링등    N01A01       인터넷PC방   R91222  ...   
573678       이/미용/건강    F01A02       발/네일케어   S96119  ...   
573679       이/미용/건강    F01A02       발/네일케어   S96119  ...   

                           건물관리번호       건물명                   도로명주소   구우편번호  \
0       1168010600106040000014378      대치상가    서울특별시 강남구 남부순환로 2933  135280   
1       1168010100106960042022041       NaN      서울특별시 강남구 선릉로93길 6  135080   
2       1154510200101620001017748       NaN      서울특별시 금천구 가산로 34-6  153010   
3       2653010400105780000002037  산업용품유통상가        부산광역시 사상구 괘감로 37  617726   
4       1171010500102560005010490       NaN        서울특별시 송파구 가락로 71  138846   
...                           ...       ...                     ...     ...   
573675  1144010200101050067001710       NaN     서울특별시 마포구 마포대로14길 4  121801   
573676  1120011500102890015004255  으뜸프린팅(주)     서울특별시 성동구 성수일로8길 37  133834   
573677  1168010800101650008000001      한맥빌딩      서울특별시 강남구 강남대로 492  135825   
573678  1156011000100230000000001  서울국제금융센터     서울특별시 영등포구 국제금융로 10  150945   
573679  1132010700108120000018489   현대타운아파트  서울특별시 도봉구 도봉로114길 22-8  132691   

          신우편번호  동정보  층정보  호정보          경도         위도  
0        6280.0  NaN    1  NaN  127.061026  37.493922  
1        6149.0  NaN    1  NaN  127.047883  37.505675  
2        8545.0  NaN    1  NaN  126.899220  37.471711  
3       46977.0  NaN    1   26  128.980455  35.159774  
4        5690.0  NaN    1  NaN  127.104071  37.500249  
...         ...  ...  ...  ...         ...        ...  
573675   4211.0  NaN  NaN  NaN  126.955059  37.548618  
573676   4794.0  NaN    2  NaN  127.054615  37.545853  
573677   6119.0  NaN    2  NaN  127.024102  37.506202  
573678   7326.0  NaN    1  NaN  126.924863  37.525172  
573679   1455.0  101  NaN  NaN  127.035145  37.647099  

[573680 rows x 39 columns]

1) 데이터 구성


2) 데이터 4가지
- int64
- float64
- object : str
- category: 문자열을 수치화

In [4]:
data.info() #갯수, 결측값 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 573680 entries, 0 to 573679
Data columns (total 39 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   상가업소번호     573680 non-null  int64  
 1   상호명        573679 non-null  object 
 2   지점명        76674 non-null   object 
 3   상권업종대분류코드  573680 non-null  object 
 4   상권업종대분류명   573680 non-null  object 
 5   상권업종중분류코드  573680 non-null  object 
 6   상권업종중분류명   573680 non-null  object 
 7   상권업종소분류코드  573680 non-null  object 
 8   상권업종소분류명   573680 non-null  object 
 9   표준산업분류코드   539290 non-null  object 
 10  표준산업분류명    539290 non-null  object 
 11  시도코드       573680 non-null  int64  
 12  시도명        573680 non-null  object 
 13  시군구코드      573680 non-null  int64  
 14  시군구명       573680 non-null  object 
 15  행정동코드      573680 non-null  int64  
 16  행정동명       573680 non-null  object 
 17  법정동코드      573680 non-null  int64  
 18  법정동명       573680 non-null  object 
 19  지번코드       573680 non-n

- haed, tail, sample 로 실제 데이터 구성 확인

In [7]:
data.head()

상가업소번호            상호명         지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드  상권업종중분류명  \
0  19905471         와라와라호프         NaN         Q       음식       Q09      유흥주점   
1  19911397  커피빈코리아선릉로93길점  코리아선릉로93길점         Q       음식       Q12    커피점/카페   
2  19911801           프로포즈         NaN         Q       음식       Q09      유흥주점   
3  19912201       싱싱커피&토스트         NaN         Q       음식       Q07     패스트푸드   
4  19932756       가락사우나내스낵         NaN         F    생활서비스       F09  대중목욕탕/휴게   

  상권업종소분류코드     상권업종소분류명 표준산업분류코드  ...                     건물관리번호       건물명  \
0    Q09A01        호프/맥주   I56219  ...  1168010600106040000014378      대치상가   
1    Q12A01  커피전문점/카페/다방   I56220  ...  1168010100106960042022041       NaN   
2    Q09A01        호프/맥주   I56219  ...  1154510200101620001017748       NaN   
3    Q07A10        토스트전문   I56192  ...  2653010400105780000002037  산업용품유통상가   
4    F09A02   사우나/증기탕/온천   S96121  ...  1171010500102560005010490       NaN   

                  도로명주소   구우편번호    신우편번호  동정보 층정보  호정보          경도         위도  
0  서울특별시 강남구 남부순환로 2933  135280   6280.0  NaN   1  NaN  127.061026  37.493922  
1    서울특별시 강남구 선릉로93길 6  135080   6149.0  NaN   1  NaN  127.047883  37.505675  
2    서울특별시 금천구 가산로 34-6  153010   8545.0  NaN   1  NaN  126.899220  37.471711  
3      부산광역시 사상구 괘감로 37  617726  46977.0  NaN   1   26  128.980455  35.159774  
4      서울특별시 송파구 가락로 71  138846   5690.0  NaN   1  NaN  127.104071  37.500249  

[5 rows x 39 columns]

In [8]:
data.tail()

상가업소번호       상호명  지점명 상권업종대분류코드  상권업종대분류명 상권업종중분류코드      상권업종중분류명  \
573675  16394290   비파티세리공덕  NaN         Q        음식       Q01            한식   
573676  16336474     앤탑PC방  NaN         N  관광/여가/오락       N01  PC/오락/당구/볼링등   
573677  16336218  오즈아레나PC방  NaN         N  관광/여가/오락       N01  PC/오락/당구/볼링등   
573678  16335152    파인트리네일  NaN         F     생활서비스       F01       이/미용/건강   
573679  16335150    마이리틀네일  NaN         F     생활서비스       F01       이/미용/건강   

       상권업종소분류코드   상권업종소분류명 표준산업분류코드  ...                     건물관리번호  \
573675    Q01A01  한식/백반/한정식   I56111  ...  1144010200101050067001710   
573676    N01A01     인터넷PC방   R91222  ...  1120011500102890015004255   
573677    N01A01     인터넷PC방   R91222  ...  1168010800101650008000001   
573678    F01A02     발/네일케어   S96119  ...  1156011000100230000000001   
573679    F01A02     발/네일케어   S96119  ...  1132010700108120000018489   

             건물명                   도로명주소   구우편번호   신우편번호  동정보  층정보  호정보  \
573675       NaN     서울특별시 마포구 마포대로14길 4  121801  4211.0  NaN  NaN  NaN   
573676  으뜸프린팅(주)     서울특별시 성동구 성수일로8길 37  133834  4794.0  NaN    2  NaN   
573677      한맥빌딩      서울특별시 강남구 강남대로 492  135825  6119.0  NaN    2  NaN   
573678  서울국제금융센터     서울특별시 영등포구 국제금융로 10  150945  7326.0  NaN    1  NaN   
573679   현대타운아파트  서울특별시 도봉구 도봉로114길 22-8  132691  1455.0  101  NaN  NaN   

                경도         위도  
573675  126.955059  37.548618  
573676  127.054615  37.545853  
573677  127.024102  37.506202  
573678  126.924863  37.525172  
573679  127.035145  37.647099  

[5 rows x 39 columns]

In [9]:
data.sample()

상가업소번호   상호명  지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드 상권업종중분류명 상권업종소분류코드  \
195897  24895298  아이엠펫  NaN         S       의료       S04      수의업    S04A02   

       상권업종소분류명 표준산업분류코드  ...                     건물관리번호  건물명  \
195897     동물병원   M73100  ...  2650010100104120040015027  NaN   

                     도로명주소   구우편번호    신우편번호  동정보  층정보  호정보          경도  \
195897  부산광역시 수영구 과정로 62-1  613130  48218.0    2  NaN  NaN  129.107517   

               위도  
195897  35.176932  

[1 rows x 39 columns]

In [6]:
data.describe()

상가업소번호           시도코드          시군구코드         행정동코드         법정동코드  \
count  5.736800e+05  573680.000000  573680.000000  5.736800e+05  5.736800e+05   
mean   2.044501e+07      15.348348   15763.525241  1.576413e+09  1.576364e+09   
std    5.205697e+06       6.805672    6764.853061  6.764838e+08  6.764853e+08   
min    2.890524e+06      11.000000   11110.000000  1.111052e+09  1.111010e+09   
25%    1.607177e+07      11.000000   11320.000000  1.132068e+09  1.132011e+09   
50%    2.212026e+07      11.000000   11620.000000  1.162058e+09  1.162010e+09   
75%    2.479404e+07      26.000000   26230.000000  2.623051e+09  2.623010e+09   
max    2.852486e+07      26.000000   26710.000000  2.671033e+09  2.671033e+09   

               지번코드         대지구분코드          지번본번지          지번부번지  \
count  5.736800e+05  573680.000000  573680.000000  474924.000000   
mean   1.576365e+18       1.001337     469.281810      33.526514   
std    6.764852e+17       0.036540     484.778049     109.050559   
min    1.111010e+18       1.000000       1.000000       1.000000   
25%    1.132011e+18       1.000000     109.000000       3.000000   
50%    1.162010e+18       1.000000     335.000000       9.000000   
75%    2.623010e+18       1.000000     678.000000      25.000000   
max    2.671033e+18       2.000000    9999.000000    9992.000000   

              도로명코드          건물본번지         건물부번지          구우편번호  \
count  5.736800e+05  573680.000000  71988.000000  573680.000000   
mean   1.576388e+11     153.912094      6.957479  273865.589341   
std    6.764847e+10     276.980935      9.799897  215630.650361   
min    1.111020e+11       0.000000      1.000000  100011.000000   
25%    1.132041e+11      20.000000      1.000000  134856.000000   
50%    1.162030e+11      50.000000      3.000000  142876.000000   
75%    2.623020e+11     172.000000      9.000000  604042.000000   
max    2.671042e+11    3318.000000    250.000000  619963.000000   

               신우편번호             경도             위도  
count  573671.000000  573680.000000  573680.000000  
mean    17531.336024     127.596287      36.854698  
std     19418.733839       0.941262       1.081285  
min      1000.000000     126.768169      35.006760  
25%      4385.000000     126.968316      35.215422  
50%      6517.000000     127.047672      37.511207  
75%     46567.000000     128.986938      37.560362  
max     49527.000000     129.292243      37.692398

- 필요한 부분을 가져옴 

### 열 선택
 - attribute - Series
 - dictionary - Series
 - fancy indexing - DataFrame

In [11]:
data.시도코드 #attribute -series

0         11
1         11
2         11
3         26
4         11
          ..
573675    11
573676    11
573677    11
573678    11
573679    11
Name: 시도코드, Length: 573680, dtype: int64

In [12]:
data['시도코드'] #dict -series

0         11
1         11
2         11
3         26
4         11
          ..
573675    11
573676    11
573677    11
573678    11
573679    11
Name: 시도코드, Length: 573680, dtype: int64

In [13]:
data[['시도코드']] #fancy indexing - DataFrame

시도코드
0         11
1         11
2         11
3         26
4         11
...      ...
573675    11
573676    11
573677    11
573678    11
573679    11

[573680 rows x 1 columns]

### 행 
- haed,tail, sample - DataFrame
- loc[n] : n=index 이름
    - index 기반이므로 해당한 index slicing 할때 전체 포함함
- iloc[n]: 위치 숫자
    - indexing : Series
    - slicing  : DataFrame
    
    > Numpy indexing, slicing 기법:
        - [,], [][], boolean indexing,[[ ]], [...] 

In [27]:
data.tail().iloc[0] #tail의 0번째 데이터

상가업소번호                        16394290
상호명                            비파티세리공덕
지점명                                NaN
상권업종대분류코드                            Q
상권업종대분류명                            음식
상권업종중분류코드                          Q01
상권업종중분류명                            한식
상권업종소분류코드                       Q01A01
상권업종소분류명                     한식/백반/한정식
표준산업분류코드                        I56111
표준산업분류명                        한식 음식점업
시도코드                                11
시도명                              서울특별시
시군구코드                            11440
시군구명                               마포구
행정동코드                       1144056500
행정동명                               공덕동
법정동코드                       1144010200
법정동명                               공덕동
지번코드               1144010200201050067
대지구분코드                               1
대지구분명                               대지
지번본번지                              105
지번부번지                               67
지번주소              서울특별시 마포구 공덕동 105-67
도로명코드                    

In [28]:
data.tail().iloc[0:] #tail 전체

상가업소번호       상호명  지점명 상권업종대분류코드  상권업종대분류명 상권업종중분류코드      상권업종중분류명  \
573675  16394290   비파티세리공덕  NaN         Q        음식       Q01            한식   
573676  16336474     앤탑PC방  NaN         N  관광/여가/오락       N01  PC/오락/당구/볼링등   
573677  16336218  오즈아레나PC방  NaN         N  관광/여가/오락       N01  PC/오락/당구/볼링등   
573678  16335152    파인트리네일  NaN         F     생활서비스       F01       이/미용/건강   
573679  16335150    마이리틀네일  NaN         F     생활서비스       F01       이/미용/건강   

       상권업종소분류코드   상권업종소분류명 표준산업분류코드  ...                     건물관리번호  \
573675    Q01A01  한식/백반/한정식   I56111  ...  1144010200101050067001710   
573676    N01A01     인터넷PC방   R91222  ...  1120011500102890015004255   
573677    N01A01     인터넷PC방   R91222  ...  1168010800101650008000001   
573678    F01A02     발/네일케어   S96119  ...  1156011000100230000000001   
573679    F01A02     발/네일케어   S96119  ...  1132010700108120000018489   

             건물명                   도로명주소   구우편번호   신우편번호  동정보  층정보  호정보  \
573675       NaN     서울특별시 마포구 마포대로14길 4  121801  4211.0  NaN  NaN  NaN   
573676  으뜸프린팅(주)     서울특별시 성동구 성수일로8길 37  133834  4794.0  NaN    2  NaN   
573677      한맥빌딩      서울특별시 강남구 강남대로 492  135825  6119.0  NaN    2  NaN   
573678  서울국제금융센터     서울특별시 영등포구 국제금융로 10  150945  7326.0  NaN    1  NaN   
573679   현대타운아파트  서울특별시 도봉구 도봉로114길 22-8  132691  1455.0  101  NaN  NaN   

                경도         위도  
573675  126.955059  37.548618  
573676  127.054615  37.545853  
573677  127.024102  37.506202  
573678  126.924863  37.525172  
573679  127.035145  37.647099  

[5 rows x 39 columns]

In [31]:
data.tail().loc[573675 :573676]#573675 ~573678 추출

상가업소번호      상호명  지점명 상권업종대분류코드  상권업종대분류명 상권업종중분류코드      상권업종중분류명  \
573675  16394290  비파티세리공덕  NaN         Q        음식       Q01            한식   
573676  16336474    앤탑PC방  NaN         N  관광/여가/오락       N01  PC/오락/당구/볼링등   

       상권업종소분류코드   상권업종소분류명 표준산업분류코드  ...                     건물관리번호  \
573675    Q01A01  한식/백반/한정식   I56111  ...  1144010200101050067001710   
573676    N01A01     인터넷PC방   R91222  ...  1120011500102890015004255   

             건물명                도로명주소   구우편번호   신우편번호  동정보  층정보  호정보  \
573675       NaN  서울특별시 마포구 마포대로14길 4  121801  4211.0  NaN  NaN  NaN   
573676  으뜸프린팅(주)  서울특별시 성동구 성수일로8길 37  133834  4794.0  NaN    2  NaN   

                경도         위도  
573675  126.955059  37.548618  
573676  127.054615  37.545853  

[2 rows x 39 columns]

In [5]:
import seaborn as sns
tips=sns.load_dataset('tips')
tips.tail(10).iloc[:-3,:2]

total_bill   tip
234       15.53  3.00
235       10.07  1.25
236       12.60  1.00
237       32.83  1.17
238       35.83  4.67
239       29.03  5.92
240       27.18  2.00

- Numpy [ , ]

In [8]:
tips.tail(10).loc[234:257,'total_bill':'day'] #이름 기반

total_bill   tip     sex smoker   day
234       15.53  3.00    Male    Yes   Sat
235       10.07  1.25    Male     No   Sat
236       12.60  1.00    Male    Yes   Sat
237       32.83  1.17    Male    Yes   Sat
238       35.83  4.67  Female     No   Sat
239       29.03  5.92    Male     No   Sat
240       27.18  2.00  Female    Yes   Sat
241       22.67  2.00    Male    Yes   Sat
242       17.82  1.75    Male     No   Sat
243       18.78  3.00  Female     No  Thur

In [10]:
tips.tail(10).at[241,'day'] #이름 기반

'Sat'

In [12]:
tips.smoker=='No'

0       True
1       True
2       True
3       True
4       True
       ...  
239     True
240    False
241    False
242     True
243     True
Name: smoker, Length: 244, dtype: bool

In [13]:
tips[tips.smoker=='No'] #boolean indexing

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
235       10.07  1.25    Male     No   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[151 rows x 7 columns]

- 2개 이상의 조건 `()` 구분
    - & and , | or

In [14]:
tips[(tips.smoker=='No') & (tips.time=='Dinner')] #boolean indexing

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
235       10.07  1.25    Male     No   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[106 rows x 7 columns]

In [21]:
tips[(tips.smoker=='No') | (tips.time=='Dinner')] #boolean indexing

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[221 rows x 7 columns]

In [20]:
tips['size'].value_counts()

2    156
3     38
4     37
5      5
6      4
1      4
Name: size, dtype: int64

In [18]:
tips.time.value_counts() 

Dinner    176
Lunch      68
Name: time, dtype: int64

In [19]:
tips.smoker.value_counts()

No     151
Yes     93
Name: smoker, dtype: int64

In [1]:
import numpy as np
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a[a>4] #boolean indexing

array([ 5,  6,  7,  8,  9, 10, 11])

In [35]:
a[(0,2),(2,1)] #인덱싱

array([2, 9])

In [36]:
np.all([1,2,1]) #모든 원소가 True(존재론적)

True

In [4]:
np.any([0,0,0]) #원소 하나라도 False(존재록적)

False

In [39]:
np.nonzero([2,0,1]) #0아닌 값 인덱스 반환

(array([0, 2]),)

In [2]:
np.where(a>4) #SQL Where 연관지으면 쉬움

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))

In [40]:
np.where((a>3)&(a<5))  # 3<a<5 -> a=4 

(array([1]), array([0]))

In [42]:
a[1,0] #상동

4

In [46]:
np.where(True,1,2) #조건이 맞으며 1 아니면 2

array(1)

In [47]:
np.where([True,True], 
         [1,2],[3,4])

array([1, 2])

In [45]:
np.where([True,False], 
         [1,2],[3,4])

array([1, 4])

In [44]:
np.where([[True,False],[True,True]], 
         [[1,2],[3,4]],[[5,6],[7,8]])

array([[1, 6],
       [3, 4]])

In [27]:
np.where(a>4,a,0) #4보다 크면 해당 값 작으면 0

array([[ 0,  0,  0,  0],
       [ 0,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 인덱스를 추출

In [67]:
np.where(tips.day=='Thur') #index 추출

(array([ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 191, 192, 193, 194, 195, 196,
        197, 198, 199, 200, 201, 202, 203, 204, 205, 243]),)

In [68]:
tips.loc[np.where(tips.day=='Thur')] #index 추출한것 이용해서 indexing

total_bill   tip     sex smoker   day    time  size
77        27.20  4.00    Male     No  Thur   Lunch     4
78        22.76  3.00    Male     No  Thur   Lunch     2
79        17.29  2.71    Male     No  Thur   Lunch     2
80        19.44  3.00    Male    Yes  Thur   Lunch     2
81        16.66  3.40    Male     No  Thur   Lunch     2
..          ...   ...     ...    ...   ...     ...   ...
202       13.00  2.00  Female    Yes  Thur   Lunch     2
203       16.40  2.50  Female    Yes  Thur   Lunch     2
204       20.53  4.00    Male    Yes  Thur   Lunch     4
205       16.47  3.23  Female    Yes  Thur   Lunch     3
243       18.78  3.00  Female     No  Thur  Dinner     2

[62 rows x 7 columns]

In [59]:
tips[tips.day=='Fri']

total_bill   tip     sex smoker  day    time  size
90        28.97  3.00    Male    Yes  Fri  Dinner     2
91        22.49  3.50    Male     No  Fri  Dinner     2
92         5.75  1.00  Female    Yes  Fri  Dinner     2
93        16.32  4.30  Female    Yes  Fri  Dinner     2
94        22.75  3.25  Female     No  Fri  Dinner     2
95        40.17  4.73    Male    Yes  Fri  Dinner     4
96        27.28  4.00    Male    Yes  Fri  Dinner     2
97        12.03  1.50    Male    Yes  Fri  Dinner     2
98        21.01  3.00    Male    Yes  Fri  Dinner     2
99        12.46  1.50    Male     No  Fri  Dinner     2
100       11.35  2.50  Female    Yes  Fri  Dinner     2
101       15.38  3.00  Female    Yes  Fri  Dinner     2
220       12.16  2.20    Male    Yes  Fri   Lunch     2
221       13.42  3.48  Female    Yes  Fri   Lunch     2
222        8.58  1.92    Male    Yes  Fri   Lunch     1
223       15.98  3.00  Female     No  Fri   Lunch     3
224       13.42  1.58    Male    Yes  Fri   Lunch     2
225       16.27  2.50  Female    Yes  Fri   Lunch     2
226       10.09  2.00  Female    Yes  Fri   Lunch     2

### 중복값

In [60]:
tips.duplicated

<bound method DataFrame.duplicated of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [61]:
tips.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [62]:
tips[tips.duplicated()]

total_bill  tip     sex smoker   day   time  size
202        13.0  2.0  Female    Yes  Thur  Lunch     2

In [66]:
tips.duplicated(keep=False).sum() #True =1이므로  겹치는것 2개

2

In [64]:
tips[tips.duplicated(keep=False)]

total_bill  tip     sex smoker   day   time  size
198        13.0  2.0  Female    Yes  Thur  Lunch     2
202        13.0  2.0  Female    Yes  Thur  Lunch     2