# [ICTCOG] 4기 경북대 기본반

- [파이썬 공식문서]https://docs.python.org/ko/3/

## Numpy (4)
- Numpy 공식문서  the Absolute basics for beginnersTutorial 로 공부하기


In [1]:
import numpy as np

In [2]:
a= np.arange(12).reshape(3,4)

### Stacking
- `append, concatenate, stack, hstack, vstack, dstack`
    - `append`: container 아니여도 추가됨
- 각각의 미묘한 차이 알아야함
    - 차원 추가
         - `stack`, `dstack`
   - `axis=0` 열 결합
       - `r_`, `append(axis=0)`, `concatenate(axis=0)`,`vstack`,`row_stack`
   - `axis=1` 행 결합
       - `c_`, `append(axis=1)`, `concatenate(axis=1)`,`hstack` ,`column_stack`

#### np.r_
- indexer 인덱스처럼 사용 `np.r_[, ]`
- 연산자 오버로딩,오버라이딩 가능

In [3]:
np.r_[a,a] #함수 아니고 클래스 인스턴스

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
type(np.r_)

numpy.lib.index_tricks.RClass

In [13]:
np.append(a,a,axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
np.concatenate((a,a),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
np.vstack((a,a))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.row_stack((a,a))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### np.c_

In [115]:
np.c_[a,a[-1]]  # column 추가함

array([[ 0,  1,  2,  3,  4,  5, 30],
       [ 6,  7,  8,  9, 10, 11, 31],
       [12, 13, 14, 15, 16, 17, 32],
       [18, 19, 20, 21, 22, 23, 33],
       [24, 25, 26, 27, 28, 29, 34],
       [30, 31, 32, 33, 34, 35, 35]])

In [24]:
np.c_[a,a]

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [27]:
np.append(a,a,axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [30]:
np.concatenate((a,a),axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [29]:
np.hstack((a,a))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [31]:
np.column_stack((a,a))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

- method 보다 function
    - mutable 하는 순간 바뀌어버려서 함수형 패러다임 사용
    
### Splitting
- `np.split, np.hsplit, np.vsplit`
#### np.split
- array 를 원하는 크기만큼 나눔
- `Signature: np.split(ary, indices_or_sections, axis=0)`
 > - Machine Learing : hold-out(2-way, 3-way hold-out) technique

In [48]:
np.split(a,3) #행 기준

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [41]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
np.split(a,2,axis=1) #열 기준

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

##### len technique
- 데이터가 복잡할 수록 데이터가 어떻게 구성되는지 모름
- **len 길이만큼 unpacking 가능**

In [51]:
len(np.split(a,2,axis=1)) # 2개로 나누어진것을 알 수 있음-> 2개로 unpacking 가능

2

In [54]:
x,y=np.split(a,2,axis=1)
x,y

(array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]]))

- 없는 경우 `array([], shape=(3, 0), dtype=int32)]`

In [58]:
np.split(a,(2,4),axis=1) #array 3개 

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]]),
 array([], shape=(3, 0), dtype=int32)]

In [59]:
np.split(a,(2,2),axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([], shape=(3, 0), dtype=int32),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

#### np.vsplit
- 행 기반 분리 (split vertically)

In [63]:
a=np.arange(36).reshape(6,6)

In [64]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

#### np.hsplit
- 열 기반 분리 (split horizontally)

In [67]:
np.hsplit(a,3) 

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

### Transpose
- 행렬의 전치 `T, np.transpose`
- **행, 열 바꿈**
    - `T` 단순하게 행,열 전치 
    -  `np.transpose`: axes 어떤 dimension 바꾸는지 지정

In [68]:
a.T

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [71]:
a.transpose()   

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [72]:
np.transpose(a)

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [74]:
np.transpose(a,(0,1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [75]:
np.transpose(a,(1,0))

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [91]:
x= np.arange(24).reshape(2,3,4)
np.transpose(x, (1, 0, 2)).shape  # axis 따라서 바뀌는 것을 알 수 있음.

(3, 2, 4)

In [92]:
x #2,4,4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [93]:
x.T  #4.4.2

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [95]:
x=np.arange(24).reshape(4,6)

### 차원 추가
- `reshape ,np.expand_dims, np.newaixs`

#### reshape
- reshape( `1` ) :1 을 원래 shape 에 원하는 위치에 넣어 추가 
    - N 차원 : N+1가지
        - Matlab 방식

In [96]:
x.reshape(1,4,6) #shape(1,4,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [100]:
x.reshape(4,1,6) #shape (4,1,6)

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23]]])

In [98]:
x.reshape(4,6,1) #shape(4,6,1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15],
        [16],
        [17]],

       [[18],
        [19],
        [20],
        [21],
        [22],
        [23]]])

- CNN 3차원 데이터 입력을 받고 ML 2차원 데이터 입력을 받음
    - 2차원 데이터를 3차원 데이터로 변경해줘야함

#### np.expand_dims
- array에 정해진 axis에 차원 추가
-  `np.expand_dims(a, axis)` 
- 직관적 (용도가 뚜렷)
    - > `reshape()`

In [119]:
np.expand_dims(x,0)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [117]:
np.expand_dims(x,1)

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23]]])

In [118]:
np.expand_dims(x,2)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15],
        [16],
        [17]],

       [[18],
        [19],
        [20],
        [21],
        [22],
        [23]]])

#### np.newaixs[]
- `[]`이용해서 새로운 axis 추가
    > `[:]` == `[,,,]` ==` `
- `None` 과 동일하나 더 명시적

In [122]:
x[np.newaxis][:]

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [123]:
x[np.newaxis]

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [124]:
x[np.newaxis][...]

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [126]:
x[:,np.newaxis]

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23]]])

In [128]:
x[:,:,np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15],
        [16],
        [17]],

       [[18],
        [19],
        [20],
        [21],
        [22],
        [23]]])

In [129]:
x[...,np.newaxis] # x[:,:,np.newaxis] 동일

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15],
        [16],
        [17]],

       [[18],
        [19],
        [20],
        [21],
        [22],
        [23]]])

In [132]:
np.newaxis #return None

In [134]:
print(np.newaxis)

None


In [137]:
np.newaxis is None

True

In [136]:
x[None] 

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

TensorFlow 예시에 다양한 방법으로 차원 추가를 함

#### @ 
- python foundation제단에서 넘파이를 위해서 연산자로 만들어줌
- 원래 decorator 문법규칙

[Numpy Overview] (https://numpy.org/doc/stable/user/quickstart.html#functions-and-methods-overview)

 --- 
 
### Data Types
 - C로 만들어서 C data type 사용 가능[data type] (https://numpy.org/doc/stable/user/basics.types.html)

In [139]:
import platform #platform dependent (eg. win :float 32, Mac:float 64)

In [140]:
dir(platform) #Mac, Win32, java,linux 따라 상이

['_WIN32_CLIENT_RELEASES',
 '_WIN32_SERVER_RELEASES',
 '__builtins__',
 '__cached__',
 '__copyright__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__version__',
 '_comparable_version',
 '_component_re',
 '_default_architecture',
 '_follow_symlinks',
 '_ironpython26_sys_version_parser',
 '_ironpython_sys_version_parser',
 '_java_getprop',
 '_libc_search',
 '_mac_ver_xml',
 '_node',
 '_norm_version',
 '_platform',
 '_platform_cache',
 '_pypy_sys_version_parser',
 '_sys_version',
 '_sys_version_cache',
 '_sys_version_parser',
 '_syscmd_file',
 '_syscmd_uname',
 '_syscmd_ver',
 '_uname_cache',
 '_ver_output',
 '_ver_stages',
 'architecture',
 'collections',
 'java_ver',
 'libc_ver',
 'mac_ver',
 'machine',
 'node',
 'os',
 'platform',
 'processor',
 'python_branch',
 'python_build',
 'python_compiler',
 'python_implementation',
 'python_revision',
 'python_version',
 'python_version_tuple',
 're',
 'release',
 'sys',
 'system',
 'system_alias',
 'un

- 데이터 타입 단축표현 

In [143]:
np.array([1,2,3]).dtype 

dtype('int32')

In [144]:
np.sctypeDict.keys() #단축 표현

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'int64', 'Int64', 'i8', 'uint64', 'Uint64', 'u8', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'UInt64', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 

### Structured Array
- tensorflow int 64, float 32
- 정의한 데이터 타입 만들 수 있음

### np.array
- np.array (  (data )  dtype= [(이름 ,데이터 타입)....])

- [Numpy Tutorials: Numpy Basics: Structured arrays](https://numpy.org/doc/stable/user/basics.rec.html)

- list 대신에 tuple(immutable container) 사용
   - column 딕셔너리 방식
   - row    인덱싱

In [168]:
data=np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
...              dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
data

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

##### 정형데이터 형태

|name|age|weight|
|----|---|-----|
|Rex |9  |81.0|
|Fido|3  |27.0|

In [169]:
np.array([1,2,3],dtype='i8')

array([1, 2, 3], dtype=int64)

In [171]:
data['name'] #이름에 해당하는 값 가져옴

array(['Rex', 'Fido'], dtype='<U10')

In [172]:
data.name #. 접근 불가

AttributeError: 'numpy.ndarray' object has no attribute 'name'

In [178]:
data[0] #row/field 추출

('Rex', 9, 81.)

In [179]:
data[:] #slicing  가능

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [181]:
data[['name','age']] #fancy indexing 

array([('Rex', 9), ('Fido', 3)],
      dtype={'names':['name','age'], 'formats':['<U10','<i4'], 'offsets':[0,40], 'itemsize':48})

In [182]:
type(data)

numpy.ndarray

### np.rec.array
- ndarray 상속받음
- record arrays
    - column 딕셔너리 방식, **attribute방식**
    - row    인덱싱

In [183]:
data2= np.rec.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
...              dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [184]:
data2 #rec.array

rec.array([('Rex', 9, 81.), ('Fido', 3, 27.)],
          dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [185]:
issubclass(type(data2),np.ndarray)

True

In [186]:
data2['age']

array([9, 3])

In [187]:
data2.age #. 접근(attribute 방식) 이제 가능

array([9, 3])

---

## Pandas 
- 프로그래밍 방식으로 **빅데이터 전처리(preprocessing),분석(analysis)**
- 모든 정형데이터의 기본 데이터

In [2]:
import pandas as pd

### seaborn
- pandas format 기반으로 그래프, 연습용 데이터 제공

- 연습용 데이터 tips
    - 직사각형의 2차원형태의 정형화된 데이터
    - 통계 분석, 기계 학습의 기본적 데이터 포맷


In [3]:
import seaborn as sns #pandas format 기반으로 그래프

### DataFrame
- 각 행별로 색상이 상이함
- 직사각형 형태의 테이블
-  Numpy 의 np.rec.array 기반
    - Python의 Excel 
        - Excel 은 큰 데이터에 적합하지 않음
- index, 0~ N
- index, column, header 

In [27]:
tips=sns.load_dataset('tips') 
tips 

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [204]:
type(tips)

pandas.core.frame.DataFrame

In [205]:
tips['tip'] 

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

### Series
- index, value 로 보여줌
- 열: `table.column`
- 행: `table.iloc[i], table.loc[i]`

In [194]:
tips.tip #np.rec.array기반 attribute 방식

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [206]:
type(tips.tip) #Series 타입

pandas.core.series.Series

In [202]:
tips.iloc[1] #1번째 행의 데이터

total_bill     10.34
tip             1.66
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 1, dtype: object

In [203]:
tips.loc[1]

total_bill     10.34
tip             1.66
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 1, dtype: object

In [195]:
tips[['tip','sex']]

tip     sex
0    1.01  Female
1    1.66    Male
2    3.50    Male
3    3.31    Male
4    3.61  Female
..    ...     ...
239  5.92    Male
240  2.00  Female
241  2.00    Male
242  1.75    Male
243  3.00  Female

[244 rows x 2 columns]

#### values
- DataFrame, Series 를 array -> Numpy

In [207]:
tips.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [208]:
tips.tip.values

array([ 1.01,  1.66,  3.5 ,  3.31,  3.61,  4.71,  2.  ,  3.12,  1.96,
        3.23,  1.71,  5.  ,  1.57,  3.  ,  3.02,  3.92,  1.67,  3.71,
        3.5 ,  3.35,  4.08,  2.75,  2.23,  7.58,  3.18,  2.34,  2.  ,
        2.  ,  4.3 ,  3.  ,  1.45,  2.5 ,  3.  ,  2.45,  3.27,  3.6 ,
        2.  ,  3.07,  2.31,  5.  ,  2.24,  2.54,  3.06,  1.32,  5.6 ,
        3.  ,  5.  ,  6.  ,  2.05,  3.  ,  2.5 ,  2.6 ,  5.2 ,  1.56,
        4.34,  3.51,  3.  ,  1.5 ,  1.76,  6.73,  3.21,  2.  ,  1.98,
        3.76,  2.64,  3.15,  2.47,  1.  ,  2.01,  2.09,  1.97,  3.  ,
        3.14,  5.  ,  2.2 ,  1.25,  3.08,  4.  ,  3.  ,  2.71,  3.  ,
        3.4 ,  1.83,  5.  ,  2.03,  5.17,  2.  ,  4.  ,  5.85,  3.  ,
        3.  ,  3.5 ,  1.  ,  4.3 ,  3.25,  4.73,  4.  ,  1.5 ,  3.  ,
        1.5 ,  2.5 ,  3.  ,  2.5 ,  3.48,  4.08,  1.64,  4.06,  4.29,
        3.76,  4.  ,  3.  ,  1.  ,  4.  ,  2.55,  4.  ,  3.5 ,  5.07,
        1.5 ,  1.8 ,  2.92,  2.31,  1.68,  2.5 ,  2.  ,  2.52,  4.2 ,
        1.48,  2.  ,

#### to_numpy
- 데이터 프레임을 numpy로 변경
- `tips.to_numpy( dtype=None, copy: bool = False,...)`
    
- 데이터 타입, copy 등의 옵션을 줌

In [209]:
tips.to_numpy(copy=False) #copy ,view

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [211]:
iris= sns.load_dataset('iris')
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [213]:
iris.columns #column 은 index!

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

### column 뽑는 방법
1. dict
2. attribute 방식
3. fancy indexing
    > Numpy record array에서 옴

In [224]:
iris['sepal_width']

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [226]:
iris.sepal_width

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

- fancy indexing 은 Series 아닌 DataFarme

In [227]:
tips[['tip','size']] # fancy indexing

tip  size
0    1.01     2
1    1.66     3
2    3.50     3
3    3.31     2
4    3.61     4
..    ...   ...
239  5.92     3
240  2.00     2
241  2.00     2
242  1.75     2
243  3.00     2

[244 rows x 2 columns]

#### row 뽑는 방법
1. iloc
2. loc

In [218]:
iris.index #0~150개의 index

RangeIndex(start=0, stop=150, step=1)

In [219]:
iris.iloc[1]

sepal_length       4.9
sepal_width          3
petal_length       1.4
petal_width        0.2
species         setosa
Name: 1, dtype: object

In [220]:
iris.loc[0]

sepal_length       5.1
sepal_width        3.5
petal_length       1.4
petal_width        0.2
species         setosa
Name: 0, dtype: object

In [221]:
iris.values

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.6, 1.4, 0.2, 'setosa'],
       [5.4, 3.9, 1.7, 0.4, 'setosa'],
       [4.6, 3.4, 1.4, 0.3, 'setosa'],
       [5.0, 3.4, 1.5, 0.2, 'setosa'],
       [4.4, 2.9, 1.4, 0.2, 'setosa'],
       [4.9, 3.1, 1.5, 0.1, 'setosa'],
       [5.4, 3.7, 1.5, 0.2, 'setosa'],
       [4.8, 3.4, 1.6, 0.2, 'setosa'],
       [4.8, 3.0, 1.4, 0.1, 'setosa'],
       [4.3, 3.0, 1.1, 0.1, 'setosa'],
       [5.8, 4.0, 1.2, 0.2, 'setosa'],
       [5.7, 4.4, 1.5, 0.4, 'setosa'],
       [5.4, 3.9, 1.3, 0.4, 'setosa'],
       [5.1, 3.5, 1.4, 0.3, 'setosa'],
       [5.7, 3.8, 1.7, 0.3, 'setosa'],
       [5.1, 3.8, 1.5, 0.3, 'setosa'],
       [5.4, 3.4, 1.7, 0.2, 'setosa'],
       [5.1, 3.7, 1.5, 0.4, 'setosa'],
       [4.6, 3.6, 1.0, 0.2, 'setosa'],
       [5.1, 3.3, 1.7, 0.5, 'setosa'],
       [4.8, 3.4, 1.9, 0.2, 'setosa'],
       [5.0, 3.0, 1.6, 0.

In [222]:
iris.to_numpy()

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.6, 1.4, 0.2, 'setosa'],
       [5.4, 3.9, 1.7, 0.4, 'setosa'],
       [4.6, 3.4, 1.4, 0.3, 'setosa'],
       [5.0, 3.4, 1.5, 0.2, 'setosa'],
       [4.4, 2.9, 1.4, 0.2, 'setosa'],
       [4.9, 3.1, 1.5, 0.1, 'setosa'],
       [5.4, 3.7, 1.5, 0.2, 'setosa'],
       [4.8, 3.4, 1.6, 0.2, 'setosa'],
       [4.8, 3.0, 1.4, 0.1, 'setosa'],
       [4.3, 3.0, 1.1, 0.1, 'setosa'],
       [5.8, 4.0, 1.2, 0.2, 'setosa'],
       [5.7, 4.4, 1.5, 0.4, 'setosa'],
       [5.4, 3.9, 1.3, 0.4, 'setosa'],
       [5.1, 3.5, 1.4, 0.3, 'setosa'],
       [5.7, 3.8, 1.7, 0.3, 'setosa'],
       [5.1, 3.8, 1.5, 0.3, 'setosa'],
       [5.4, 3.4, 1.7, 0.2, 'setosa'],
       [5.1, 3.7, 1.5, 0.4, 'setosa'],
       [4.6, 3.6, 1.0, 0.2, 'setosa'],
       [5.1, 3.3, 1.7, 0.5, 'setosa'],
       [4.8, 3.4, 1.9, 0.2, 'setosa'],
       [5.0, 3.0, 1.6, 0.

In [233]:
dir(tips)

['T',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__re

- attribute 기반은 이미 Numpy에 정의된 `size`가 반환
- descriptor 이름규칙 공백, 특수 문자,숫자 포함하면 안 됨(제한적)
    - get,set,property...
- dictionary 방식으로 추출
    - structured array에 . 대신 dictionary 제공하는 이유

In [234]:
tips.size #

1708

In [ ]:
# 공백, 특수문자,숫자 섞이면 안됨

In [5]:
tips.tip #attribute 기법

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

- indexing,slicing: view
- fancy indexing: copy  

In [6]:
tips['size']=1 #braodcasting
tips            #view

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     1
1         10.34  1.66    Male     No   Sun  Dinner     1
2         21.01  3.50    Male     No   Sun  Dinner     1
3         23.68  3.31    Male     No   Sun  Dinner     1
4         24.59  3.61  Female     No   Sun  Dinner     1
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     1
240       27.18  2.00  Female    Yes   Sat  Dinner     1
241       22.67  2.00    Male    Yes   Sat  Dinner     1
242       17.82  1.75    Male     No   Sat  Dinner     1
243       18.78  3.00  Female     No  Thur  Dinner     1

[244 rows x 7 columns]

- 내부적 구현은 fancy indexing 이 아님을 알 수 있음

In [7]:
tips[['size']]=3 #reference 임
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     3
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     3
4         24.59  3.61  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     3
241       22.67  2.00    Male    Yes   Sat  Dinner     3
242       17.82  1.75    Male     No   Sat  Dinner     3
243       18.78  3.00  Female     No  Thur  Dinner     3

[244 rows x 7 columns]

In [17]:
tips[['smoker', 'tip']]

smoker   tip
day              
Sun      No  1.01
Sun      No  1.66
Sun      No  3.50
Sun      No  3.31
Sun      No  3.61
...     ...   ...
Sat      No  5.92
Sat     Yes  2.00
Sat     Yes  2.00
Sat      No  1.75
Thur     No  3.00

[244 rows x 2 columns]

#이름이 1인경우가 있어서 일반적 indexing 없음

#### loc
- 행의 label 기반 

In [31]:
tips.loc[239]

total_bill     29.03
tip             5.92
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 239, dtype: object

#### iloc 
- index based locaion

In [20]:
tips.iloc[239]

total_bill     29.03
tip             5.92
sex             Male
smoker            No
time          Dinner
size               3
Name: Sat, dtype: object

### set_index
- 다양한 인덱스 설정하도록 지원

In [11]:
tips.set_index('day',inplace=True)

In [12]:
tips

total_bill   tip     sex smoker    time  size
day                                                
Sun        16.99  1.01  Female     No  Dinner     3
Sun        10.34  1.66    Male     No  Dinner     3
Sun        21.01  3.50    Male     No  Dinner     3
Sun        23.68  3.31    Male     No  Dinner     3
Sun        24.59  3.61  Female     No  Dinner     3
...          ...   ...     ...    ...     ...   ...
Sat        29.03  5.92    Male     No  Dinner     3
Sat        27.18  2.00  Female    Yes  Dinner     3
Sat        22.67  2.00    Male    Yes  Dinner     3
Sat        17.82  1.75    Male     No  Dinner     3
Thur       18.78  3.00  Female     No  Dinner     3

[244 rows x 6 columns]